### ISSUE TITLE
Find a name for the program/url

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#1]
We could just name it *mentoring program* but maybe that's too boring?

**Comment by hennevogel** [comment]
Some ideas: 

* Bootcamp
* Davis (after [Coach Davis a.k.a. Captain Obvious](http://www.urbandictionary.com/define.php?term=Coach+Davis))
* Skipper
* Master (as in git branch...)

**Comment by hennevogel** [comment]
More ideas: 

* 101
* BYU - [Back Yard University](http://onlineslangdictionary.com/meaning-definition-of/byu)
* Ferris or [Bueller](https://en.wikipedia.org/wiki/Ferris_Bueller's_Day_Off)

**Comment by ChrisBr** [comment]
I like 101 :)

**Comment by cornelius** [comment]
Maybe something around "learning" or "growth"?

**Comment by ddemaio** [comment]
How name ideas:
apprentice
soar
tracks
mount

**Comment by hennevogel** [comment]
Okay let's decide: I like 101 best

**Comment by ChrisBr** [comment]
+1 for 101

**Comment by hennevogel** [comment]
@cornelius? :-)

**Comment by ddemaio** [comment]
+ 101

**Comment by ddemaio** [comment]
@hennevogel what's the address going to be for this 101.opensuse.org or 101.opensuse.io?

**Comment by ChrisBr** [comment]
@ddemaio probably the first one, 101.opensuse.org

**Comment by hennevogel** [comment]
We own .io?

**Comment by ChrisBr** [comment]
@hennevogel you take care of this, right?

**Comment by hennevogel** [comment]
Jupp the request is running

**Comment by hennevogel** [comment]
http://101.opensuse.org it is!
