### ISSUE TITLE
Integrate cloud pinyin in ibus-pinyin or ibus-libpinyin

### ISSUE THREAD

**Issue by hillwoodroc** [openSUSE/mentoring#100]
**Project Title:** Integrate cloud pinyin in ibus-pinyin or ibus-libpinyin

**Description:** 

Pinyin input method is the most popular input method in China. There are many kinds of Pinyin input methods on ibus, such as ibus-pinyin, ibus-libpinyin and ibus-sunpinyin. All of them need search words from local table dictionary.

What is ibus? The full name of ibus is Input Bus Introduction. It is the default input method framework in SUSE Linux Enterprise and openSUSE GNOME Desktop. ibus-pinyin and ibus-libpinyin work on ibus. ibus and its input method are very important to Asia users of SUSE Linux Enterprise and openSUSE.

The cloud computing is the new feature in some commercial input methods in China. They can search and get words from cloud server. Cloud computing can greatly improve the accuracy of the input method.

This idea is integrating cloud computing in ibus-pinyin or ibus-libpinyin. Many cloud pinyin input methods have apis can be used, Such as sougoupinyin, baidupinyin and googlepinyin. And Fcitx have finished this work, but it was just a extension on fcitx (fcitx-cloudpinyin).

**Deliverable:** 

Create and send your patch to us. We will test it. If it's stable, we can help you to merge it to upstream. So, Merged by upstream is the best.

**Mentor:** @hillwoodroc @qiangzhao

**Skills:** C, C++, python3, autotools.(Maybe javascript and HTML)

**Skill Level:** Medium/Hard

**Get started:** 

- IBus 1.5 API: https://github.com/ibus/ibus/wiki

- Source of libpinyin: https://github.com/libpinyin/libpinyin

- Source of ibus-libpinyin: https://github.com/libpinyin/ibus-libpinyin

- Source of pyzy: https://github.com/pyzy/pyzy

- Source of ibus-pinyin: https://github.com/ibus/ibus-pinyin

- Refer：https://github.com/fcitx/fcitx-cloudpinyin

**Comment by ChrisBr** [comment]
@hillwoodroc maybe you can elaborate a little bit how this is already used by openSUSE or how openSUSE is related?

**Comment by hillwoodroc** [comment]
@ChrisBr I add this paragraph in description, is it ok?

> What is ibus? The full name of ibus is Input Bus Introduction. It is the default input method framework in SUSE Enterprise and openSUSE GNOME Desktop. ibus-pinyin and ibus-libpinyin work on ibus. The ibus and it's input method is very import to Asia users of SUSE Enterprise and openSUSE.

**Comment by hillwoodroc** [comment]
Thank you, @ChrisBr

**Comment by Ana06** [comment]
@ChrisBr should we add again the Other projects section which I remove in https://github.com/openSUSE/mentoring/pull/90/commits/db4237655ab80f7255ee246d0b53213cf9cd5a7b to show this project in the main page as well? I think it doesn't make sense to have a specific section for it, right? 🤔

**Comment by hillwoodroc** [comment]
@Ana06 I think you could set "M17N" label instead of "other". This is a M17N project.

**Comment by ChrisBr** [comment]
@hillwoodroc labelling with M17N does not make any difference if there is no section for it (the label just makes sure that it gets added to the right section here http://101.opensuse.org/). As I saw that @Ana06  already added the Other section again it should be fine. Otherwise feel free to send a pull request with a M17N section (I can't do it because I don't know anything about it ...).

**Comment by Ana06** [comment]
Closing as this project is from last year. Please open a new one if this is still a current project. :wink:

**Comment by qiangzhao** [comment]
> Closing as this project is from last year. Please open a new one if this is still a current project. wink

There's no problem for me. 
Thank you, Ana!
