### ISSUE TITLE
ssl certificate on 101.opensuse.org expired

### ISSUE THREAD

**Issue by medwinz** [openSUSE/mentoring#104]
Ssl certificate on 101.opensuse.org is expired. Please renew it :-)

**Comment by lagartoflojo** [comment]
Starting today, [GH pages do have SSL support](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). But the domain needs to be configured with a CNAME rather than an A record. See the warning message under the "GitHub Pages" section of this project's settings.

**Comment by lagartoflojo** [comment]
SSL is now enabled via Let's Encrypt.
