### ISSUE TITLE
EOS Web UI builder

### ISSUE THREAD

**Issue by cyntss** [openSUSE/mentoring#106]
**Project Title:** Web UI builder

**Description:** EOS Design System is an open source set of guidelines, components, elements, and more. All these tools are there to help developers and designers create products in a consistent and efficient way. The goal of a Design System is that all products in a portfolio look and feel the same in order to enhance the user experience and brand perception. While a good documentation of all these components help designers and developers understand how and when to use them, nothing could make their life easier than enabling developers and designers to create quick mockups in an online web UI builder that use the exact color, size, and shape of the UI block defined in the design system.

There is already an open source web builder available: https://github.com/artf/grapesjs. You can checkout the demo at: https://grapesjs.com/demo.html. And several other proprietary builders:
https://www.layoutit.com/build, https://pingendo.com/
Use the examples above to get the best ideas for the UI builder, keeping in mind that we expect a more minimal result given the size of a project like that, so you will need to plan this accordingly. We will help you.

EOS follows the Atomic Design process for building UI blocks:

![image](https://user-images.githubusercontent.com/5013096/49255397-2c134980-f42c-11e8-852b-9bc32e4aa743.png)

If you want to understand more about Atomic Design, I recommend you reading the following article: https://medium.muz.li/building-design-systems-with-atomic-design-93a13286f676

**Deliverable:** The main objective of this project is to deliver a basic web UI builder that can easily register new UI elements, and that can export mockups (perhaps just a PDF or screenshot at first).

**Mentor:** Cynthia Sanchez. Co-mentor: Sorin Curescu.

**Skills:** Node.js, Express.js, CI, Angular/React/Backbone, Pug.js, SCSS, Bootstrap 4, Heroku.

**Skill Level:** Medium

**Get started:** Research and test the waters first. Grapesjs may not be the only open source available solution. Start small and keep a close communication gap with your mentors, we are entirely available for you. Your success is our main priority.

**Comment by Ana06** [comment]
As [openSUSE is not going to participate in GSoC this year](https://lists.opensuse.org/opensuse-project/2019-02/msg00006.html), I will close this issue to avoid confusion (I received emails asking about it).

**Comment by cyntss** [comment]
@Ana06 could you please forward those emails to me or tell the people that contacted you to join the mailing list: https://groups.google.com/forum/#!forum/eos-design-system, where they can get in touch with us ?

**Comment by Ana06** [comment]
@cyntss they were interesting in participating in GSoC and were asking if we will participate. I have just answered saying we are not participating this year.
