### ISSUE TITLE
GSoC link broken

### ISSUE THREAD

**Issue by ikapelyukhin** [openSUSE/mentoring#107]
GSoC link (https://101.opensuse.org/gsoc) in the header and footer are broken -- they redirect to `http://101.cf.infra.opensuse.org/gsoc/`, which doesn't resolve and HTTPS is being downgraded to HTTP:

```
curl -v 'https://101.opensuse.org/gsoc'
> GET /gsoc HTTP/1.1
> Host: 101.opensuse.org
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Length: 178
< Content-Type: text/html
< Date: Fri, 30 Nov 2018 11:14:58 GMT
< Location: http://101.cf.infra.opensuse.org/gsoc/
< Server: nginx
< X-Vcap-Request-Id: 0b545509-1d18-485e-636f-14f97a88523e
< Strict-Transport-Security: max-age=15768000
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

https://101.opensuse.org/gsoc/ (note the trailing slash) works fine, though.

Is the site deployed with CloudFoundry? Something is fishy with the setup.

**Comment by Ana06** [comment]
It is deployed with GithubPages :confused:

**Comment by ikapelyukhin** [comment]
@Ana06 it doesn't seem to be hosted by GitHub though.

```
# nslookup 101.opensuse.org

Non-authoritative answer:
101.opensuse.org	canonical name = proxy.opensuse.org.
proxy.opensuse.org	canonical name = proxy-nue.opensuse.org.
Name:	proxy-nue.opensuse.org
Address: 195.135.221.140
Name:	proxy-nue.opensuse.org
Address: 2620:113:80c0:8::16
```

**Comment by Ana06** [comment]
That's what Gihub says: https://github.com/openSUSE/mentoring/deployments :rofl:

**Comment by Ana06** [comment]
@hennevogel and @ChrisBr may know more about it... :thinking:

**Comment by ikapelyukhin** [comment]
@Ana06 hmm, I'm not seeing my changes on the live site yet :thinking:
