### ISSUE TITLE
Mixed content - fonts loaded via http

### ISSUE THREAD

**Issue by cboltz** [openSUSE/mentoring#109]
_includes/head.html contains

    <link href="http://fonts.googleapis.com/css?family=Lato:[...]

Since 101.o.o uses https, this results in a "mixed content" warning and not loading the fonts.

I see two options to fix that:
- boring - change "http" to "https" in the quoted line
- more work, but better IMHO: switch to the fonts we use everywhere in openSUSE, and load them from static.o.o.

**Comment by hennevogel** [comment]
three: 

* use a protocol relative url lile `//fonts.googleapis.com/css`...

**Comment by hellcp** [comment]
this can be closed, since we don't load any fonts now
