### ISSUE TITLE
Native Ruby Interface for libyui

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/mentoring#11]
**Description:** There is libyui library which provides single interface for three toolkits (QT, GTK and ncurses). It is heavily used in YaST and also Mageia uses that for its configuration tool. YaST is now transpiled to ruby and libyui ruby bindings is simple 1:1 to its C++ API. Goal of this project is to design and implement native ruby API built on top of libyui.

**Deliverable:** It is expected that at the end of project there will be design of library, proposal for API and implementation for basic widgets.

**Mentor:** @jreidinger / jreidinger@suse.cz

**Skills:** Knowledge of ruby idioms and basic ruby libraries - to have idea how good ruby design look like API design

**Skill Level:** Medium

**Getting started:** Look at existing frameworks and its API like [shoes](https://github.com/shoes/shoes4), [dsl-gtk](https://github.com/glurp/dsl-gtk) or [hello-rugui](http://blog.rugui.org/2009/01/hello-rugui/ hello-rugui/) and then post to yast-devel@opensuse.org mailing list own proposal how new API can look like together with at least two examples of code that uses such API.

**Github:** https://github.com/yast/

**Comment by art-solopov** [comment]
Hello!
I have about 1 year and 10 months of experience as a Ruby on Rails developer, although I've never actually created a lib API.
I love Ruby and I'd love to contribute to OpenSUSE!

**Comment by ancorgs** [comment]
@art-solopov nice to read that! Just drop by the #yast irc channel at Freenode (also reachable as irc.opensuse.org) so we can discuss the details. Most YaST developers are there on working days between 9h and 18h (CET).

See you there!

**Comment by art-solopov** [comment]
@ancorgs Oh dear. I usually work during the same hours. :disappointed: I'll try my best to reach you.

**Comment by jreidinger** [comment]
In such case you can also reach us via mailing list on yast-devel@opensuse.org just expect some time to answer

**Comment by art-solopov** [comment]
Thank you!

**Comment by ChrisBr** [comment]
@ancorgs & @jreidinger is this one still valid? If yes please open a new issue! Thanks!
