### ISSUE TITLE
Merge cloud input feature into ibus-libpinyin

### ISSUE THREAD

**Issue by hillwoodroc** [openSUSE/mentoring#117]
**Project Title:** Merge cloud input feature into ibus-libpinyin

**Description:** We had a GSoC project about integration cloud pinyin in ibus-libpinyin at 2018. A student got this project and achieved this feature. The code is at https://github.com/openSUSE/ibus-libpinyin. But it was not merged to upstream due to some special demands and methods. We hope somenone can finally finish this project and merge this feature to upstream.
What is ibus? The full name of ibus is Input Bus Introduction. It is the default input method framework in SUSE Linux Enterprise and openSUSE GNOME Desktop. ibus-pinyin and ibus-libpinyin work on ibus. ibus and its input method are very important to Asia users of SUSE Linux Enterprise and openSUSE.

**Deliverable:** Please work on github. We will test you code. If it's stable, we can help you to merge it to upstream. 

**Mentor:**  @epico @qiangzhao  @hillwoodroc

**Skills:** C, C++, python3, autotools.

**Skill Level:** Medium/Hard

**Get started:** 
 
- IBus 1.5 API: https://github.com/ibus/ibus/wiki
- Source of libpinyin: https://github.com/libpinyin/libpinyin
- Source of ibus-libpinyin: https://github.com/libpinyin/ibus-libpinyin

**Comment by Inokinoki** [comment]
Hi there, I've succeeded in building the mentioned repo with the cloud input feature.
Could you please tell me, what are those special demands and methods that blocked its merge to the upstream? I may be able to do some work :)

**Comment by hillwoodroc** [comment]
1. Please use some techique to verify the data returned from third-
party web site
  2. Please use asynchronized communication with web site
  3. Please use glib/gnome library to connect to web site

**Comment by Inokinoki** [comment]
Great appreciation!

For the 3rd one, AFAIK, `libsoup` is already a lib maintained by Gnome.

I've suffered some crash during the test of sync requests to Baidu cloud input source, with Google source it works well.
Since their responses are both JSON, can I use the JSON parser lib in Glib to do some validations and to avoid the crash? (rather than the string splitting solution in the current version)

**Comment by hillwoodroc** [comment]
I think it is feasible. But I don't know think other two mentors how think it. I suggest you to email us.

**Comment by epico** [comment]
Yeah, GLib JSON library is one option.

For me, public discussion is okay; other students can also see the information.

**Comment by qiangzhao** [comment]
> Yeah, GLib JSON library is one option.
> 
> For me, public discussion is okay; other students can also see the information.

Me too!

**Comment by epico** [comment]
Here are some partial cloud input TODO list from me.

  1. With GLib JSON library, I think it is better to check the data member in JSON
     a. if possible please check as many data field as possible;

  2. Please use asynchronized communication with web site
     a. insert one cloud symbol before web site returning data;
     b. replace the cloud symbol with the data returned from web site;
     c. what will happen if multiple web request is sent?

Sorry, I will try to find some time to update the detailed TODO list later.

**Comment by Inokinoki** [comment]
I've done an initial json validation:
https://github.com/Inokinoki/ibus-libpinyin/blob/5bd41ddfd08a85d0857a20ba8957b67d62928115/src/PYPCloudCandidates.cc#L245
Adding more.

For the async request, I'm still investigating how it can work to replace the candidates.

I've already tested the case to send multiple web request in async mode. Maybe it's possible to add a send timestamp as a part of user data, drop the other replies and use the latest one.

I'm also wondering how it can act when a request fails(error request, incomplete response, invalid format). Will it be intelligent to remove the candidates?

**Comment by epico** [comment]
Could you organize the code into two class for Google and Baidu Parser?
It is okay to put the two class in PYPCloudCandidates.cc.

I think timestamp may be dropped by web site, but not very sure.
Maybe you could compare the user input returned from the web site.

If the web request fails, we need to notice the user with some symbol.
Then we can get issue report from user.

**Comment by Inokinoki** [comment]
> Could you organize the code into two class for Google and Baidu Parser?
> It is okay to put the two class in PYPCloudCandidates.cc.
> 
> I think timestamp may be dropped by web site, but not very sure.
> Maybe you could compare the user input returned from the web site.

Done:
https://github.com/Inokinoki/ibus-libpinyin/blob/5ccf75beaf43a388e78fb3d755e3114a2bbf05aa/src/PYPCloudCandidates.cc#L53

I'm planning to handle the failures and add symbol in [`CloudCandidates::processCloudResponse`](https://github.com/Inokinoki/ibus-libpinyin/blob/5ccf75beaf43a388e78fb3d755e3114a2bbf05aa/src/PYPCloudCandidates.cc#L218). After this, the functionalities should have been completed.

And the file is nearly ready to be reviewed. Don't hesitate if you have any advise.

Then, I'm going to do something with setup ui, to make cloud input more configurable.

**Comment by Inokinoki** [comment]
What do you think if we have a cloud unicode icon for the candidates like this:
[enhanced.m_display_string = "☁..."](https://github.com/Inokinoki/ibus-libpinyin/blob/26c61092c153dc3208e4550058735d8407306fd2/src/PYPCloudCandidates.cc#L63).

**Comment by hillwoodroc** [comment]
I agree.

**Comment by Inokinoki** [comment]
Done.

![Screenshot_20200307_113521](https://user-images.githubusercontent.com/8311300/76141783-cb7baf00-6067-11ea-9b2b-6c1e35836a5a.png)

I'm making a pull request for review.

**Comment by hillwoodroc** [comment]
It can work on double pinyin mode.
![2020-03-09 11-05-28屏幕截图](https://user-images.githubusercontent.com/1880237/76179495-162b3180-61f6-11ea-843f-cc713eaafdea.png)
![2020-03-09 11-04-36屏幕截图](https://user-images.githubusercontent.com/1880237/76179497-17f4f500-61f6-11ea-8ce4-85915179c758.png)

**Comment by epico** [comment]
Here are more suggestions coming. ;)

1. Please add one option for some time delay before sending the web request
   a. I mean if the user is inputting, better delay the web request

2. Please cancel the web request, if the user changes the input after web request sent
   a. Maybe soup_session_cancel_message is helpful

For double pinyin, I can provide some code snippets by using libpinyin later.

Feel free to ping me, if you have any questions.

**Comment by Inokinoki** [comment]
> Here are more suggestions coming. ;)
> 
>     1. Please add one option for some time delay before sending the web request
>        a. I mean if the user is inputting, better delay the web request
Good I idea, I was considering it. But what is the best delay? Should it be better to make it configurable?

>     2. Please cancel the web request, if the user changes the input after web request sent
>        a. Maybe soup_session_cancel_message is helpful
> 
Yes, it could be helpful!
I didn't realize that can be cancelled as I thought in the sync request flow. I agree that this can bring better user experience.

**Comment by Inokinoki** [comment]
> It can not work on double pinyin mode.
> ![2020-03-09 11-05-28屏幕截图](https://user-images.githubusercontent.com/1880237/76179495-162b3180-61f6-11ea-843f-cc713eaafdea.png)
> ![2020-03-09 11-04-36屏幕截图](https://user-images.githubusercontent.com/1880237/76179497-17f4f500-61f6-11ea-8ce4-85915179c758.png)

Fixed.

**Comment by epico** [comment]
Yes, I think the time delay should be configurable.

Maybe only configurable in gsettings is also okay.

**Comment by hillwoodroc** [comment]
I give you two suggestions on the pull request https://github.com/libpinyin/ibus-libpinyin/pull/228/files

**Comment by Inokinoki** [comment]
Thanks for all your suggestions!

I've submitted a draft proposal for this idea. Don't hesitate if you have any question or advice :)
