### ISSUE TITLE
the post of ibus project could not display its image.

### ISSUE THREAD

**Issue by qiangzhao** [openSUSE/mentoring#118]
Hi:
I have sent a post on the iBus project, but unfortunately, the image could not display, Who could the reason please?  what should i do in addition?
Thank you!

https://github.com/openSUSE/mentoring/pull/116

**Comment by hennevogel** [comment]
`mv img/ibus.png img/projects/ibus.png`

**Comment by hennevogel** [comment]
Fixed now

**Comment by qiangzhao** [comment]
Thank you so much!
