### ISSUE TITLE
Container-based backend for openQA

### ISSUE THREAD

**Issue by okurz** [openSUSE/mentoring#120]
**Project Title:** Container-based backend for openQA

**Description:**

[openQA](https://open.qa) is an automated test tool for operating systems and the engine at the heart of openSUSE's automated testing initiative. It provides already several backends that allows testing an O.S. on a variety of architectures and scenarios including baremetal and different kinds of virtualized environment.

A backend capable of directly interacting with different containers technologies would allow us to test container images before release - that could be really useful and enhance the development and publication workflow of containerized environments. 

The new container backend ideally should provide an abstract interface to allow [os-autoinst](https://github.com/os-autoinst/os-autoinst) and the test cases to interact with the specific container technology ( that could be Kubernetes, Rancher, podman, Docker, LXD/LXC, rkt, etc. ) and provide the same integration to our current workflow (e.g. tests that runs under a VM).

If you haven't already, [have a look at openQA in action](https://openqa.opensuse.org).

**Deliverable:** Code is merged with the necessary tests to prove each feature created. Abstract interface design and at least one specific backend container implementation is expected.

**Mentor:** @okurz, @kalikiana

**Skills:** podman/docker, a bit of Perl, some general knowledge of containerized environment and container management frameworks

**Skill Level:** Medium

**Get started:**

* Engage with the development team! We hang out in https://app.element.io/#/room/#openqa:opensuse.org and [#opensuse-factory](irc://libera.chat/opensuse-factory) on Libera.Chat!

* Start forking the [openQA](https://github.com/os-autoinst/openQA) and the [os-autoinst](https://github.com/os-autoinst/os-autoinst) repo

* General hints and advices for good project proposals:
  * https://google.github.io/gsocguides/student/writing-a-proposal
  * https://hackernoon.com/7-things-you-need-to-know-to-ace-your-gsoc-proposal-92ff7ef23f5a
  * https://medium.com/oppia-org/things-i-learned-from-reviewing-gsoc-proposals-154707cdcca5

**Comment by KevinKipkorir** [comment]
Hello, This is a fun project I would really like to work on as I have recently had an interest in containerization and virtualization. Could  you please suggest some repo concerning this project to get familiar with the work of this task.

**Comment by okurz** [comment]
@KevinKipkorir hi, happy to hear about your interest. The above description has some links included within the text for repos concerning this project that you can follow.

**Comment by KevinKipkorir** [comment]
@okurz Hi, I submitted a  draft proposal for this project. Could you care to go through it and advice what you think of it before i go on an submit a final Proposal. Thank you.

**Comment by okurz** [comment]
Thank you for the draft proposal. General hints and advices for good project proposals:
  * https://google.github.io/gsocguides/student/writing-a-proposal
  * https://hackernoon.com/7-things-you-need-to-know-to-ace-your-gsoc-proposal-92ff7ef23f5a
  * https://medium.com/oppia-org/things-i-learned-from-reviewing-gsoc-proposals-154707cdcca5

**Comment by okurz** [comment]
@ddemaio Our GSOC project was not yet finished and the idea can still be tried again in another GSOC period. I think it might be cleaner to open a new issue for that though. Do you agree?

**Comment by ddemaio** [comment]
Sounds good @okurz. I'll reopen it and tag openQA. I'll make a note that openQA is interested in mentoring for 22. We have two other teams as well.

**Comment by ddemaio** [comment]
Hi @okurz   I listed this as a large sized project. About 175 hrs for the student for the medium size and 350 hrs for a large project. Please change it if it isn't correct.

**Comment by akshat5302** [comment]
Hey, @okurz I would like to contribute to this project as a part of gsoc22. I have intermediate knowledge of containers and container management tools as well. Please provide me with some resources or guidance to quickstart with this project I'm very much excited to contribute to this project

**Comment by okurz** [comment]
Hi @akshat5302, please see the "Get started"-section in https://github.com/openSUSE/mentoring/issues/120#issue-559559713 . This also mentions our chat room where you can address me and us and have a nice chat where we can further support you.

**Comment by akshat5302** [comment]
Actually I have some family matter due to which I haven't seen your comment early

**Comment by akshat5302** [comment]
Actually gsoc proposal deadline has been closed could I send you my
proposal personally by tomorrow if possible ?

I have some family matter due to which I haven't seen your mail early

Please look into this mail and hope to get a positive response from your
side

Regards
Akshat Jain

**Comment by foursixnine** [comment]
@akshat5302 submit it through the system, I can't commit to reviewing your proposal tomorrow, so I think it's better if you prepare one, following @okurz's comment on the Getting started section.

**Comment by mukul-kr** [comment]
> @ddemaio Our GSOC project was not yet finished and the idea can still be tried again in another GSOC period. I think it might be cleaner to open a new issue for that though. Do you agree?

Can you please provide me with the details about what part of this issue is available to work on? Can you also share the reference for the previous year's work?

**Comment by ddemaio** [comment]
> > @ddemaio Our GSOC project was not yet finished and the idea can still be tried again in another GSOC period. I think it might be cleaner to open a new issue for that though. Do you agree?
> 
> Can you please provide me with the details about what part of this issue is available to work on? Can you also share the reference for the previous year's work?

@okurz?

**Comment by okurz** [comment]
> > @ddemaio Our GSOC project was not yet finished and the idea can still be tried again in another GSOC period. I think it might be cleaner to open a new issue for that though. Do you agree?
> 
> Can you please provide me with the details about what part of this issue is available to work on? 

Hi @mukul-kr, the issue description was updated since then and is up-to-date. All that is referenced can theoretically be worked on. However we can also adapt the specific content during the project execution.
Please see the "Get started"-section in https://github.com/openSUSE/mentoring/issues/120#issue-559559713 . This also mentions our chat room where you can address me and us and have a nice chat where we can further support you.

> Can you also share the reference for the previous year's work?

Good question. But there was actually no relevant contribution that can be shared.

**Comment by foehammer127** [comment]
Will this be listed again?

**Comment by okurz** [comment]
the project will be covered as part of GSOC 2023. We don't plan to offer it again for next years.
