### ISSUE TITLE
Convert Virtual Systems page to ReactJS

### ISSUE THREAD

**Issue by paususe** [openSUSE/mentoring#124]
**Project Title:** Convert Virtual Systems page to ReactJS

**Description:** The Uyuni web interface is mostly implemented based on aging technologies like JSP while the new pages are written in ReactJS. The goal of this project is to add the missing ReactJS components, like a tree table and reimplement the Systems > System List > Virtual Systems page in ReactJS. Of course the page will need some fresh paint to be prettier and be more useful.

This task is also likely to touch the database queries to optimize them when displaying the page for big number of virtual hosts and machines.

**Deliverable:** The result of this project will consist in one or more pull requests to the Uyuni repository implementing a working ReactJS version of the page.

The newly created reusable ReactJS components will need to be provided with a story and documentation to explain how to use them.

**Mentor:** @cbosdo

**Skills:** ReactJS and Java. Hibernate and SQL are a plus.

**Skill Level:** Medium

**Get started:** 
Installing the development environment:

* https://github.com/uyuni-project/uyuni/wiki/Java-Development-Environment
* https://github.com/uyuni-project/uyuni/wiki/Frontend-Development-Environment

Installing a test environment:

* https://github.com/uyuni-project/sumaform

Code pointers to get started:

* JSP to replace: https://github.com/uyuni-project/uyuni/blob/master/java/code/webapp/WEB-INF/pages/systems/virtuallist.jsp
* Java code behind the JSP: https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/frontend/action/systems/VirtualSystemSetupAction.java
* ReactJS pages routing: https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/suse/manager/webui/Router.java.
* Code of the ReactJS components and pages: https://github.com/uyuni-project/uyuni/blob/master/web/html/src/
* Slides on how to get started developing Uyuni: http://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/about
* Uyuni Wiki:
  * Introduction to Uyuni and systems management (presentation): https://github.com/uyuni-project/uyuni/wiki/Presentations
  * Uyuni development in no time: https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time
  * Development pages: https://github.com/uyuni-project/uyuni/wiki/

**Comment by chauhanparth210** [comment]
Hello @paususe, 

I am Parth Chauhan(@chauhanparth210) and I am a third-year ICT (Information and Communication Technology) student, currently pursuing B.Tech degree form DA-IICT, India. I have worked a lot with Javascript and proficient in MERN(Mongodb, Express.js, React.js and Node.js) stack. I am  familier 
with Java and c++. I have good knowledge of database too.

I came across GSoC website and I went through your open source projects . I found this project Convert Virtual Systems page to ReactJS interesting and want to contribute to this project.

Thank you.

**Comment by paususe** [comment]
Hello Parth

Glad you are interested! I'd suggest you install Uyuni, take a look at the Virtual Systems page, and then set up a development environment. If you need any help, ping us here or in Gitter or in IRC

https://www.uyuni-project.org/pages/contact.html

Thank you

Pau Garcia Quiles
SUSE Manager Product Owner & Technical Project Manager
Phone: +34 91 9018066
SUSE Software Solutions Spain


________________________________
De: Parth P. Chauhan <notifications@github.com>
Enviado: domingo, 22 de marzo de 2020 08:30
Para: openSUSE/mentoring <mentoring@noreply.github.com>
Cc: Pau Garcia Quiles <pau.garcia@suse.com>; Mention <mention@noreply.github.com>
Asunto: Re: [openSUSE/mentoring] Convert Virtual Systems page to ReactJS (#124)


Hello @paususe<https://github.com/paususe>,

I am Parth Chauhan(@chauhanparth210<https://github.com/chauhanparth210>) and I am a third-year ICT (Information and Communication Technology) student, currently pursuing B.Tech degree form DA-IICT, India. I have worked a lot with Javascript and proficient in MERN(Mongodb, Express.js, React.js and Node.js) stack. I am familier
with Java and c++. I have good knowledge of database too.

I came across GSoC website and I went through your open source projects . I found this project Convert Virtual Systems page to ReactJS interesting and want to contribute to this project.

Thank you.

**Comment by cbosdo** [comment]
@chauhanparth210 not sure you will see the above message

**Comment by sshiv5768** [comment]
Hey, @paususe  I am interested to work with this issue.

**Comment by cbosdo** [comment]
@sshiv5768 This one is already being worked on by @riyakalra for Google Summer of Code.
