### ISSUE TITLE
Improve Uyuni Documentation Publishing Theme

### ISSUE THREAD

**Issue by paususe** [openSUSE/mentoring#125]
**Project Title:** Project title, short enough to catch attention

**Description:** Use our existing Antora theme to learn our publishing process. Then with input from our team, design a modern, classy theme that meets SUSE documentation standards.

**Deliverable:** You will create a modern frontend for Uyuni documentation

**Mentor:** @jcayouette

**Skills:** You will need to have a good understanding of Linux, and be comfortable with version control using git and github. You will be working with Asciidoc, so learning the basics of this markdown style will be useful. Antora utilizes the Asciidoctor API to publish static HTML pages from asciidoc sources.

* Javascript (Required)
* HTML (Required)
* CSS (Required)
* Asciidoc (Basic)
* YAML (Helpful)
* Handlebars Templating (Helpful)

**Skill Level:** Medium

**Get started:**

* https://github.com/uyuni-project/uyuni-docs
* https://antora.org/
* https://asciidoctor.org/
* https://asciidoctor.github.io/asciidoctor.js/master/
* https://asciidoctor-docs.netlify.com/asciidoctor.js/
* https://handlebarsjs.com/
* https://gitter.im/antora/users

**Comment by ChetanManda** [comment]
Hello Community at Suse,

I am Chetan Manda, a final year undergraduate student from IIT Guwahati, India.
I came across NV Access on the Gsoc website and I went through your open source work and found it really interesting. I found this project to Improve Uyuni's documentation publishing theme particularly intriguing.

I am a designer and I specialize in User Interface and User Experience design(UI/UX).
I have interned at various companies during the last four years and have executed end to end projects while interacting with key stakeholders, product managers, and developers.
Here's a list of things that I do:
•Conduct User Research, develop low - high-fidelity wireframes, storyboards, user flows, screen flows, sitemaps, UI artefacts, prototyping and Usability testing.
•Create exceptional user experiences for end-users and design internal/external user-facing products ensuring they are useful and usable by end-users.  
•Translate the concepts and agreed ideas into artwork and designs that bring simplicity and user-friendliness to complex design roadblocks.   
•Basic CSS, HTML
Here are a few of my works : https://www.behance.net/ChetanManda

I would love to work for your organization on any projects/tickets that I could help out on based on my abilities. I can put in 35-40 hours per work with proper dedication throughout the Summer and I am capable of learning new languages at a pretty fast pace. I would be really grateful if you could recommend any relevant work in this project for me. Thanks in advance!

Cheers,
Chetan

**Comment by paususe** [comment]
hi @ChetanManda !

Join our Gitter room, IRC channel or uyuni-devel mailing list at we'll go from there:
https://www.uyuni-project.org/pages/contact.html

**Comment by paususe** [comment]
This was implemented by Naman Bhatia, who did a great job.
