### ISSUE TITLE
Add KDE support

### ISSUE THREAD

**Issue by cbosdo** [openSUSE/mentoring#128]
**Project Title:** Add KDE support

**Description:** Uyuni is mostly used to manage Linux servers but why not use it to manage Linux desktops?

KDE provides a number of files that can be tuned and tweaked to configure kiosk mode, background, where the task manager is, what Plasma add-ons are installed, etc.

**Deliverable:** This project is about creating Salt formulas, forms, grains, modules, pillars, etc for a sysadmin to be able to configure KDE desktops, much like a Windows sysadmin would do with Group Policy Objects.

With that, Uyuni should be able to:

* Configure basic desktop parameters such as background color/image, locale, where the task manager is, how many desktops, etc (full list to be determined after examining the KDE docs; information is a bit scattered and may be out of date)
* Install/remove Plasma add-ons and configure them
* Configure kiosk mode parameters full list to be determined after examining the KDE docs; information is a bit scattered and may be out of date) - https://userbase.kde.org/KDE_System_Administration/Kiosk/Introduction

**Mentor:** This project will be co-mentored by the KDE and Uyuni communities, as expertise from both sides will be needed.

* @davidedmundson (KDE)
* @paususe, @joesusecom, @benediktwerner

**Skills:** You will need to have a good understanding of Linux, and be comfortable with version control using git and GitHub. Python and YAML. Salt (or alike: Chef, Ansible, etc) knowledge will be a plus. Being able to read C++, Qt and KDE code will help in case the documentation is out of date and reading code is the only way to find some configuration parameter.

**Skill Level:** Medium. Technical complexity should no be that high (formulas with forms are easy to write) but locating the appropriate KDE parameters may require some digging and lots of test and error.

**Get started:** 

* Download an [Uyuni Server VM](https://download.opensuse.org/repositories/home:/pagarcia:/Uyuni/Uyuni/) and [setup the Server](https://www.uyuni-project.org/uyuni-docs/uyuni/installation/uyuni-server-setup.html)
* Read the Salt documentation: https://www.uyuni-project.org/uyuni-docs/uyuni/salt/salt-intro.html
* Download openSUSE Leap 15.1 and install it in a VM with a KDE desktop
* On the Uyuni Server, add the openSUSE repositories with spacewalk-common-channels, sync them and create a bootstrap repository. Onboard the openSUSE Leap 15.1 client.
* Go to Systems and locate your openSUSE system. Click on it and look for the Formulas tab, and the Catalogue subtab. Configure and install one formula, e. g. the locale formula. That's the kind of formulas with forms you will be writing.

**Comment by paususe** [comment]
@joesusecom and @benediktwerner will also help from the Uyuni side

**Comment by paususe** [comment]
* Getting started hacking Uyuni: http://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/about

**Comment by Chinmay4400** [comment]
Hello, I am new to OpenSUSE and after a brief reading I believe I want to be involved in this project. I am reading further from the linked resources but a question is bugging me : Uyuni seems to be a big project....do I need to have any experience with it beforehand?
Thanks.

**Comment by paususe** [comment]
Hi @Chinmay4400 !

Yes, Uyuni is a large project. None of the projects we have proposed for this GSoC edition should require previous experience (but I can assure you will learn a lot while working on them!).

This particular project is probably the one that requires the least experience, as most, of not all of the scope, should be doable by writing formulas (YAML files).

I'd recommend you take a look at the presentations page, maybe watch the videos, and try Uyuni. The easiest way is to download a VM image from the link above. Join us on Gitter, IRC or the mailing lists and we can help you if you are stuck: https://www.uyuni-project.org/pages/contact.html
