### ISSUE TITLE
Implement a proper testing framework

### ISSUE THREAD

**Issue by kstreitova** [openSUSE/mentoring#129]
**Project Title:** Implement a proper testing framework

**Description:** Currently the majority of rpmlint tests are handled via running rpmlint for built RPM packages and comparing the results. This solution has disadvantages. It's hard to maintain it, adding of new RPM test packages requires lots of effort, it doesn't scale much further and last but not least RPM packages take space in rpmlint repository.

The goal of this project is to implement a proper testing framework that would use mocking for creating new testcases instead of requiring full binary RPMs as input. The second part is to transform existing RPMs test packages into the new framework.

**Deliverable:** The result of this project will be multiple pull requests to the rpmlint repository that implement the testing framework.

**Mentor:** @kstreitova 

**Skills:** python, RPM, packaging, git, Linux

**Skill Level:** Medium/Hard

**Get started:** 
- Get familiar with the rpmlint code base and current way of testing: https://github.com/rpm-software-management/rpmlint
- Study python testing and get familiar with options we can utilize

**Comment by ddemaio** [comment]
@hennevogel could you add this

**Comment by marxin** [comment]
The project will be about an extension of the existing `FakePkg` class that supports basic mockup functionality:
https://github.com/rpm-software-management/rpmlint/blob/e6742eb2e570899bf53f1e92b686578a575249e0/rpmlint/pkg.py#L758-L799

**Comment by thisisshub** [comment]
@kstreitova Since we have the all the test cases in `pytest` for testing does that mean we just implement the rest of the **required** test cases in `pytest` as well or do we implement another testing framework from scratch?
