### ISSUE TITLE
Alternatives YaST Module

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/mentoring#13]
**Description:** openSUSE, as other distributions, includes the command update-alternatives in order to allow users to choose which program they want to be the default for every given function (which text editor, which Java implementation and so on). Being quite prominent in other distributions, update-alternatives does not get the attention it deserves in openSUSE. The project consists on implementing a YaST module for managing the alternatives and their priority, offering an easy and guided interface on top of plain update-alternatives.

**Deliverable:** A YaST module offering a clear overview of all the alternatives in the system and a convenient way to manage their configuration and priorities. The module must conform to the YaST development guidelines, which means, among other things, that it must include unit tests (RSpec).

**Mentor:** @lslezak / Ladislav Slezák and @ancorgs / ancor@suse.com

**Skills:** Ruby, Rspec, Object oriented design

**Skill Level:** Easy

**Getting started:** Read the new YaST tutorial and write question or suggestions on how to improve it to yast-devel@opensuse.org mailing list.

**Github:** https://github.com/yast/

**Comment by hennevogel** [comment]
Congratulations @jyeray this is your project for GSoC this year! :bouquet:

**Comment by jyeray** [comment]
Thanks @hennevogel and mentors @ancorgs and @jreidinger, it will be an amazing summer :smiley:
