### ISSUE TITLE
Refactor old rpmlint checks

### ISSUE THREAD

**Issue by kstreitova** [openSUSE/mentoring#130]
**Project Title:** Refactor old rpmlint checks

**Description:** The origins of rpmlint project go back to the year 1999. Even though lot's of things have been changed since that time, some rpmlint checks remained in the same shape for all that long 21 years. That means outmoded python constructs, spaghetti code, lack of comments, missings tests or just rpmlint checks that don't make any sense anymore.

The goal of this project is to review and refactor chosen rpmlint checks to use "functionalized" and modern approach. It's also needed to add basic tests before the refactoring so we are sure that there is no regression.

You will be able to choose one or more rpmlint checks that you would like to work on.
Here are some examples:

- [SpecCheck.py](https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/SpecCheck.py)
- [TagsCheck.py](https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/TagsCheck.py)
- [FilesCheck.py](https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/FilesCheck.py)
- [PostCheck.py](https://github.com/rpm-software-management/rpmlint/blob/master/rpmlint/checks/PostCheck.py)
- ...

**Deliverable:**  The result of this project will be multiple pull requests to the rpmlint repository with the refactored code and tests.

**Mentor:** @kstreitova

**Skills:** python, RPM, packaging, git, Linux

**Skill Level:** Medium

**Get started:**
- Get familiar with the rpmlint code https://github.com/rpm-software-management/rpmlint
- Choose one or more outdated rpmlint checks
- Study rpmlint checks that are already refactored to get the notion about the final state you want to reach
- Prepare tests for the rpmlint checks (one testcase per the future function)
- Refactor the old code

**Comment by thisisshub** [comment]
@kstreitova Is there a qualification task for taking up this project under Gsoc 2020?

**Comment by kstreitova** [comment]
@thisisshub No, there is no qualification task. But please note that this project requires a significant knowledge of rpm and packaging (often [openSUSE](https://en.opensuse.org/Portal:Packaging) or [Fedora](https://docs.fedoraproject.org/en-US/packaging-guidelines/) specific).

**Comment by thisisshub** [comment]
@kstreitova I am keenly interested in this project, could you help me guide into this for what should my next steps should be?

**Comment by jkauze** [comment]
Hi @kstreitova, we need to make the refactor to all  checks files or there is a minimum number required to the deliverable?

**Comment by kstreitova** [comment]
> @kstreitova I am keenly interested in this project, could you help me guide into this for what should my next steps should be?

The best start is to fulfil the prerequisites here. Which is (besides the obvious python, git and Linux) mainly RPM packaging. I don't know how familiar you are with RPM packaging but if you aren't, this is a great time to fix it. In fact, knowledge of rpm packaging is essential in this project as these rpmlint checks validate that the RPM specfile or RPM package is correct. Also, every rpmlint check needs a testcase, which is currently provided as an RPM package. Since we are missing tests for a lot of rpmlint checks, writing the new test packages will be the first thing during the refactoring (so we are sure that we didn't break anything during the refactoring. Therefore you should understand RPM and specfiles properly and be able to build your own rpm packages. 

For this purpose, you can study [RPM Packaging Guide](https://rpm-packaging-guide.github.io/) (this or any other), [openSUSE:Packaging wiki](https://en.opensuse.org/Portal:Packaging) portal and [openSUSE Packaging Guidelines](https://en.opensuse.org/openSUSE:Packaging_guidelines) where you can find all information about (openSUSE) packaging. You can also [set up](https://en.opensuse.org/openSUSE:Build_Service_Tutorial) your [OBS](https://build.opensuse.org/) account and use your home project as a playground for your packaging experiments.

The next step should be to get familiar with the rpmlint code in order to understand the structure of the program, the way how it's tested and so on. 

Then you can take a look at rpmlint checks that need a rewrite (e.g. SpecCheck.py, TagsCheck.py, FilesCheck.py, PostCheck.py etc.) and at checks that are already rewritten (e.g. LSBCheck.py, SourceCheck.py, FHSCheck.py, ZipCheck.py etc.) and you should be able to identify all these bad programming practices in the old ones :). This comparison should also help you to understand what we want to achieve here.

**Comment by kstreitova** [comment]
> Hi @kstreitova, we need to make the refactor to all checks files or there is a minimum number required to the deliverable?

It highly depends on the student's skills but I think that a good candite should finish all the 4 checks files mentioned in the initial description. But this can be affected by many circumstances since some rpmlint checks will need more research and even discussions with distributions in order to establish a "shape" of the check that would suit them all. These things and any other obstacles can't be predicted in advance though. So the results will be appraised individually. Important is student's activity, dedication, code quality, and (as we in openSUSE say) having a lot of fun! :)

If the student will work faster, there is, of course, a lot more work to do on rpmlint. We can agree on working on more checks that need improvement, speed up, documentation, tests and so on then.

**Comment by thisisshub** [comment]
@kstreitova 
Hi, I have submitted a draft proposal for review at opensuse for this project. Could you please review my proposal and add a critic. thanks!

**Comment by shenlebantongying** [comment]
> Study rpmlint checks that are already refactored to get the notion about the final state you want to reach

Can u show me an example check that are considered of state-of-art, or good a PR for a good refactor?
