### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by paususe** [openSUSE/mentoring#132]
**Project Title:** Amazon Linux 2 support

**Description:** Uyuni supports many Linux clients (openSUSE, CentOS, SUSE Linux Enterprise, Red Hat Enterprise Linux, etc). Let's add one more: Amazon Linux 2. It is very similar to RHEL but with a twist: metadata is in sqlite format. Supporting it as a Salt client is enough, no need to implement the traditional stack.

**Deliverable:** Very similar to what supporting any other client means:
* Build openSUSE's Salt packages for Amazon Linux 2. It may very well be the case that the RHEL packages just work but at least testing is needed. - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:testing/salt
* Onboard (register) Amazon Linux clients as Salt minions
* Create bootstrap repository
* Add reposync support for sqlite format. Alternatives: a) download the sqlite files and convert them to XML (which is currently works) or b) add native support for sqlite.
* Generate and process patches and security information (CVE information from the Amazon Linux Security Advisories - https://alas.aws.amazon.com/ )

**Mentor:** @juliogonzalez

**Skills:** You will need to have a good understanding of Linux, and be comfortable with version control using git and GitHub. Some Sqlite, PostgreSQL, JSON, Python and Java (you will be mostly looking at existing code and adding new sub-cases to it). Familiarity with AWS, Amazon Linux and package management.

**Skill Level:** Medium

**Get started:**
* Getting started hacking Uyuni: http://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/about
* Get a free tier account in AWS
* Read about Amazon Linux 2 and create a VM to play with it: https://aws.amazon.com/amazon-linux-2/ (you can also download and run it locally)
* Download an Uyuni Server VM and setup the Server - https://build.opensuse.org/package/binaries/home:pagarcia:Uyuni/Uyuni-2020.01-Server/Uyuni
* Hackweek project on adding support for more Linux distributions: https://hackweek.suse.com/19/projects/testing-gnu-slash-linux-distributions-on-uyuni
* Get familiar with the Uyuni source code and implement creation of the bootstrap repository. You can take a look at these commits as a reference:
https://github.com/uyuni-project/uyuni/commit/e5d4d29f3148af40882a1c726b56556f08ed41c2
https://github.com/uyuni-project/uyuni/commit/6da14873065befad4caff4e98a5f5481212fbb36
* Uyuni Wiki:
  * Introduction to Uyuni and systems management (presentation): https://github.com/uyuni-project/uyuni/wiki/Presentations
  * Development pages: https://github.com/uyuni-project/uyuni/wiki/

**Comment by juliogonzalez** [comment]
@paususe I am afraid a free tier account WON'T do it, because the Uyuni server won't run on micro instances (those are the instances you can use on a Free Tier Account). Also IIRC the Free Tier only provides 30GBs of EBS.

However, on paper, now it's possible to install Amazon Linux on premises: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html

I must say I never tested it.

**Comment by juliogonzalez** [comment]
Also for this particular test, either python should be enough (fixing the reposync problem on... reposync) or otherwise I think `C` will be required, to fix the problem on https://github.com/openSUSE/libsolv

**Comment by paususe** [comment]
> @paususe I am afraid a free tier account WON'T do it, because the Uyuni server won't run on micro instances (those are the instances you can use on a Free Tier Account). Also IIRC the Free Tier only provides 30GBs of EBS.

The free tier is for the client (Amazon Linux 2). 

The Uyuni Server can be run on your own PC and manage the cloud Amazon Linux 2 instance. Unlike some other vendors, Uyuni allows you to manage on-premise and cloud instances exactly the same.

> However, on paper, now it's possible to install Amazon Linux on premises: [docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html)
> 
> I must say I never tested it.

That's indeed another option

**Comment by juliogonzalez** [comment]
@paususe having the instance at AWS means you will be only able to manage it with salt-ssh. That's, unless you also create a VPN between your local network and AWS, or unless you expose your Uyuni instance somehow to the internet (NAT and whatnot, but I don't recommend that **AT ALL**)

So having the AWS free tier account not really useful in this case to test that things are working. Whoever does this, needs an on-premises Amazon instance, or access to an AWS account where money can be spend (not that much is required, specially if the instances are not up 24x7)

**Comment by juliogonzalez** [comment]
> Onboard (register) Debian clients as Salt minions
I updated it: `Amazon Linux 2 clients`?

**Comment by paususe** [comment]
@juliogonzalez implemented this as part of his Hackweek 20, so removing from the list of ideas.

https://hackweek.suse.com/20/projects/testing-gnu-slash-linux-distributions-on-uyuni
