### ISSUE TITLE
Refactor client OS support in kits

### ISSUE THREAD

**Issue by paususe** [openSUSE/mentoring#147]
**Project Title:** Refactor client OS support in kits

**Description:** Adding a new client OS to Uyuni is not too difficult but it requires touching code in a ton of places (see, e. g. https://github.com/paususe/uyuni/commit/492f64fca41f1292444690e8b42e16a812b28970). Most of the code for most of the clients is very repetitive. 

This project is about refactoring that into a generic code path that simpy loads "OS enablement kits". 

An OS-enablement kit would be comprised of e. g. one JSON file with the client OS name, client OS code, regular expressions needed to match /etc/os-release, the list of packages for the bootstrap repository, SQL to be inserted, etc.

**Deliverable:** Based on the above description and the existing code, implement an OSKit framework and convert the code from the existing clients (SLES, openSUSE, RHEL, CentOS, Oracle Linux, Ubuntu and Debian) to OSKits. Refinements will be needed along the way, you are not expected to get it right in the first try :-)

**Mentor:** @paususe and some other Uyuni core developer

**Skills:** A bit of Java, Python, SQL, JSON and XML will be required. Also, capacity to think in terms of generic solutions.

**Skill Level:** Medium

**Get started:** 
 * Check these links for examples of OS-enablement code:
   * Alibaba Cloud Linux 2 (complete example, includes everything) : https://github.com/uyuni-project/uyuni/commit/7d3ba0c7f9c914ac71afe2590a096f459437908a
   * Amazon Linux 2 (product identification and entitlement management is missing) : https://github.com/uyuni-project/uyuni/commit/7ac753910cff7a84d172df35bf34fb15c14fa3b4
   * Alma Linux 8 (product identification and entitlement management is missing) : https://github.com/uyuni-project/uyuni/commit/c5375e3f974fa3a8aa27ce9c2bbbd553ac12a57e
  * Uyuni development in no time: https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time
  * Uyuni wiki: https://github.com/uyuni-project/uyuni/wiki

**Comment by Tiger-0512** [comment]
Hi, @paususe 
I'm a graduate of Kyoto University and majoring CS.
I'd like to participate in Google Summer of Code 2021 at Uyuni.
In particular, I'm interested in this project.
I checked the link of `Get started`, but it doesn't work.
Could you tell me more about this project?

------------------------------------------------------------------
Taiga Matsunaga
Cognitive Informatics Laboratory
Graduate School of Informatics, Kyoto University
E-mail: matsunaga.taiga.23c@st.kyoto-u.ac.jp
------------------------------------------------------------------

**Comment by paususe** [comment]
> Hi, @paususe
> I'm a graduate of Kyoto University and majoring CS.
> I'd like to participate in Google Summer of Code 2021 at Uyuni(openSUSE).
> In particular, I'm interested in this project.
> I checked the link of `Get started`, but it doesn't work.
> Could you tell me more about this project?
> 
> Taiga Matsunaga
> Cognitive Informatics Laboratory
> Graduate School of Informatics, Kyoto University
> E-mail: [matsunaga.taiga.23c@st.kyoto-u.ac.jp](mailto:matsunaga.taiga.23c@st.kyoto-u.ac.jp)

Hello @Tiger-0512 -san!

I had merged the branch just a couple of days ago and GitHub automatically removes merged branches. I have now updated the "Get started" links with 3 examples (Alibaba Cloud Linux, Amazon Linux and Alma Linux). Sorry for the inconvenience!

**Comment by Tiger-0512** [comment]
@paususe -san ;)
Thank you for your reply!
I started with "Uyuni development in a snap: https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-a-snap
" in Get started, and try Uyuni on openSUSE.

Then, I want advice about my plan for GSoC.
This is the first time to contribute OSS, and this is my first time using Uyuni.
So I think I should start the one which is understandable.
Is it better to start `Add <some> new client OS #146`, which you mentioned?

I'm sorry I am a beginner at Uyuni.
However, I want to try because I think this is a good opportunity.

**Comment by paususe** [comment]
> @paususe -san ;)
> Thank you for your reply!
> I started with "Uyuni development in a snap: [uyuni-project/uyuni/wiki/Uyuni-development-in-a-snap](https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-a-snap)
> " in Get started, and try Uyuni to know more about it.
> 
> I have three questions, I'm happy if you answer them when you are free.
> 
>     * I want advice about my plan for GSoC. This is the first time to contribute OSS, and this is my first time using Uyuni. So I think I should start the one which is understandable. Is it better to start "Add  new client OS #146", which you mentioned?

You can start with this one, or you can add a new client operating system. Up to you. If case you want to add a new OS, this list should help you pick one:
https://github.com/uyuni-project/uyuni/wiki/Next-candidate-operating-systems

Or maybe there is a well-known enterprise Linux in Japan which I am not aware of and it would be a better candidate?

>     * Requirements of Uyuni server are very hard to build on the laptop. Do you have ways to test Uyuni clients without building a server?

For development, a VM with 8 GB RAM and 50GB disk space is enough.

At SUSE we use either public cloud or a private (internal) cloud, or just our laptops (which are quite powerful).

>     * I can't sign up openSUSE account however I tried several emails (I don't know why), so I may not be able to use OBS. (I knew To make full use of the Build Service, you need to log in with your openSUSE/SUSE account at "[en.opensuse.org/openSUSE:Build_Service_Tutorial](https://en.opensuse.org/openSUSE:Build_Service_Tutorial)".) Is it OK to use git only for contributions? or How can I use OBS?

You will need OBS, it makes everything a lot easier.

The instructions in that wiki page were obsolete, they were still linking to the old IDP tool I have now updated the link. If you are still having trouble, join or Gitter chat and ping me: https://gitter.im/uyuni-project/devel

Also, I only know how to use 20% of what that wiki page explains, so don't be overwhelmed :-O Basic usage of OBS is `osc branch`, `osc checkout`, `osc ci`, `osc add`, `osc rm`... and that's about it. I usually build using the public builders, so I'm not even using `osc build`. Most of the other functionality (repositories, project config, etc) I use from the OBS web UI.

 
> I'm sorry I am a beginner at Uyuni.
> However, I want to try because I think this is a good opportunity.

We have all been beginners at something at some point in time. Don't despair :-)

**Comment by Tiger-0512** [comment]
> You can start with this one, or you can add a new client operating system. Up to you. If case you want to add a new OS, this list should help you pick one:
https://github.com/uyuni-project/uyuni/wiki/Next-candidate-operating-systems

I decide to add a new client for my first step and get used to deal with Uyuni.
After that, I'll develop "OS enablement kits".
Thank you for your advice.

> Or maybe there is a well-known enterprise Linux in Japan which I am not aware of and it would be a better candidate?

In Japan, Ubuntu and CentOS are the most common for servers. Moreover, Fujitsu, which has the largest share of servers in Japan uses RedHat and SUSE for servers. Uyuni has already supported these four servers. So I think the supported OS is enough for Japan and other approaches are needed to spread Uyuni into Japan.

> For development, a VM with 8 GB RAM and 50GB disk space is enough.
At SUSE we use either public cloud or a private (internal) cloud, or just our laptops (which are quite powerful).

I created a partition for Uyuni server and was able to install OS. Maybe it will work well as a server.
(I have a laptop that has 8GB RAM, but it is not good to use the whole 8GM RAM in Virtual Box. So I decided to create the partition)

> You will need OBS, it makes everything a lot easier.
The instructions in that wiki page were obsolete, they were still linking to the old IDP tool I have now updated the link. If you are still having trouble, join or Gitter chat and ping me: https://gitter.im/uyuni-project/devel

I still can't log in OBS. I asked about it in https://gitter.im/uyuni-project/devel (I'm sorry that I wrote my post in the wrong channel and repost several times)

> Also, I only know how to use 20% of what that wiki page explains, so don't be overwhelmed :-O Basic usage of OBS is osc branch, osc checkout, osc ci, osc add, osc rm... and that's about it. I usually build using the public builders, so I'm not even using osc build. Most of the other functionality (repositories, project config, etc) I use from the OBS web UI.

I feel at ease to hear that. At first, I thought OBS is very complicated. I'll learn the basic functions of OBS which you told me. Thank you for your kind introduction!

**Comment by paususe** [comment]
> > For development, a VM with 8 GB RAM and 50GB disk space is enough.
> > At SUSE we use either public cloud or a private (internal) cloud, or just our laptops (which are quite powerful).
> 
> I created a partition for Uyuni server and was able to install OS. Maybe it will work well as a server.
> (I have a laptop that has 8GB RAM, but it is not good to use the whole 8GM RAM in Virtual Box. So I decided to create the partition)

I'm not sure 8GB RAM will be enough. That means your VM may have 4-5 GB RAM at best, which may cause trouble with Java. Importing packages will definitely be very very slow. 

Maybe your university offers servers or some kind of cloud you can use for development?

**Comment by Tiger-0512** [comment]
> I'm not sure 8GB RAM will be enough. That means your VM may have 4-5 GB RAM at best, which may cause trouble with Java. Importing packages will definitely be very very slow.

> Maybe your university offers servers or some kind of cloud you can use for development?

I asked my professor, but my university doesn't have such clouds which students can freely use.
