### ISSUE TITLE
Add sessions recording support to Jangouts

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/mentoring#15]
**Description:** Jangouts is a videoconferencing solution that can be used to hold meetings with any number of participants. But currently there is no way to record those meetings in order to watch them again. That's a feature that will make Jangouts suitable for many more use cases, like online workshops. This [Issue](https://github.com/jangouts/jangouts/issues/34) at GitHub describes some possible approaches to implement such feature.

**Deliverable:** A mechanism to record and play Jangouts sessions, either integrated in Jangouts itself either as an external tool that can connect to a session and produce a video out of it.

**Mentors:** @ancorgs / ancor@suse.com and @imobach / igonzalezsosa@suse.de

**Skills:** JavaScript

**Skill Level:** medium

**Getting started:** Pick something from the list of pending [features and bugs](https://github.com/jangouts/jangouts/issues) of Jangouts and try to do something about it.

**Github:** https://github.com/jangouts/jangouts/

**Comment by ancorgs** [comment]
@sandr3j I think you were interested in this project. Watch the deadline http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/  https://developers.google.com/open-source/gsoc/timeline

**Comment by ancorgs** [comment]
@sandr3j I added a comment to https://github.com/jangouts/jangouts/issues/34 that could be useful while preparing the proposal. Once again, beware the deadline (three days to go and I have not seen even a draft :wink:).

**Comment by sandr3j** [comment]
@ancorgs I uploaded now a draft. I still need to write the timeline and improve about me section. Sorry, that I'm behind the timeline. I already wanted to uploaded it sooner but thought "I just need a couple hours to finish it".

**Comment by ChrisBr** [comment]
@ancorgs & @imobachgs is this one still valid? If yes please open a new issue! Thanks!
