### ISSUE TITLE
Enhancements to the ML models

### ISSUE THREAD

**Issue by mvarlese** [openSUSE/mentoring#152]
**Project Title:** Phoebe - help increase data points density and data cleaning 

**Description:** Phoeβe (/ˈfiːbi/) wants to add basic artificial intelligence capabilities to the Linux OS. Phoeβe uses system telemetry as the input to its brain and produces a big set of settings which get applied to the running system. The decision made by the brain is continuously reevaluated (considering the grace_period setting) to offer eventually the best possible setup.

**Deliverable:** Enhancements to the ML models, help increasing data points density and data cleaning

**Mentor:** Marco Varlese <marco.varlese@suse.com>

**Skills:** Must have: C, Python, Meson, Linux - Nice-to-have: artificial-intelligence, machine-learning

**Skill Level:** Medium

**Get started:** Please, clone the code repository [1], build it with different flags set and run the code in both training and inference mode.

[1] https://github.com/SUSE/phoebe

**Comment by guptadhaval18** [comment]
@mvarlese Hi I am interested in working on this issue. Could you please explain how the Enhancements to the ML models is to be done if the model used is x*w+b as specified in readme. Also what is data point density.
Also please provide link to the data to be cleaned.

**Comment by guptadhaval18** [comment]
@mvarlese Thanks for quick response. Will be going through the repository. Will ask further questions if there is any doubt.

**Comment by guptadhaval18** [comment]
Getting build error, even though I have python3 installed.
![image](https://user-images.githubusercontent.com/47078156/110624329-0c9b2780-81c4-11eb-9961-fec54bebe781.png)

**Comment by mukul-mehta** [comment]
@mvarlese Hello, I'm interested in working on this project. To begin with, I'll build the project locally and try running it. Are there any other tasks I could take up to get more familiar with the project?

Also, is there a communication channel for discussions regarding this project?

**Comment by mvarlese** [comment]
@mukul-mehta thanks for expressing your interest. Yes, please, let's start from the activity you already depicted and possibly try to develop a basic plugin with a random functionality of your taste. That will certainly help you to familiarize with Phoebe plugin based architecture.
I do plan to establish a communication channel and will advise which one when set up.

**Comment by mukul-mehta** [comment]
Sure, I'll get to it. Thanks!

**Comment by yoBoyio** [comment]
@mvarlese Hello I'm interested in working on this project. Ηow can i contribute?
