### ISSUE TITLE
PaaS on Kubernetes

### ISSUE THREAD

**Issue by rohitsakala** [openSUSE/mentoring#153]
**Project Title:** Expanding Integration Tests on Carrier

**Description:** Carrier integrates multiple components such as gitea, tekton, traefik, eirini, registry and quarks to enable PaaS features on top of Kubernetes.

**Deliverable:** The project is just getting a UI. The task involves adding new API endpoints in GoLang and views for those using Vue.js. 

**Mentor:** Venkata Krishna Rohit Sakala <rohit.sakala@suse.com>

**Skills:** Kubernetes, GoLang, Bash, Vue.js

**Skill Level:** Medium

**Get started:** Deploy carrier locally on k3s or minikube [0]

[1] https://github.com/SUSE/carrier

**Comment by ddemaio** [comment]
@rohitsakala could you expand a little bit more on this topic. More ideas need to be flushed out rather than just contribution.

**Comment by manishdangi98** [comment]
Hi @rohitsakala I would like to work on this can you guide me from where can I start to get better understanding of the project

**Comment by rohitsakala** [comment]
> @rohitsakala could you expand a little bit more on this topic. More ideas need to be flushed out rather than just contribution.

Done. Updated the description.

**Comment by adigeak** [comment]
Hi do we have any IRC or messaging application?

**Comment by rohitsakala** [comment]
> Hi do we have any IRC or messaging application?

We do not have it now, but we planning soon.

**Comment by akshat5302** [comment]
I'm interested in this project . I'm applying for gsoc . Any tips from your side on from where to kickstart for this project .I have intermediate knowledge of linux and k8s
