### ISSUE TITLE
Update Kanidm project. 

### ISSUE THREAD

**Issue by Firstyear** [openSUSE/mentoring#154]
**Project Title**: Many Ideas with Kanidm

**Description**: Kanidm is an identity management project written in Rust. IDM services are a network store of users and groups for systems, websites and more, providing these with authentication and authorisation functionality. It aims to respect all peoples' identities and to store their data safely and correctly. IDM is a diverse area which values contributions from many people, from a variety of backgrounds. 

**Assessment**: Our intent is to mentor and help you grow as a contributor - and we want to help you succeed! As this is our focus, we have different assessment criteria to many other projects.

Has the student:
* participated actively in the project?
* written and submitted personal blog/journal or similar about the experience and what they have learnt and attempted?
* sufficiently attempted one or any of the offered deliverables? (Note - there is no requirement to *complete* the deliverable. Just evidence of a solid attempt)

**Deliverable**: As IDM spans many areas, we offer multiple possible focus areas. You should select one of these areas.

There is no requirement to complete *all* of these - we want you to attempt to work in an area of interest to you, and if you wish to change focus during the project, we can negotiate altering or changing which deliverable is your focus. 

Possible deliverable areas (choose one):

* Documentation and Accessibility - Improvements to project documentation, --help text, design of the user interface and command line tools, and extension of the CLI with new functionality.
* HTTP Api Development - improve the usability, performance and features of the REST api attached to the server.
* Database Performance - creation of a statistics collection and analysis process that can assist a query optimiser in improving query performance. 
* Rust FFI for RADIUS - rewrite the current RLM python module into Rust, with C-ffi bindings. 
* Your choice - there are many ideas in our issue tracker which you can choose from. Alternately, suggest your own! https://github.com/kanidm/kanidm/issues

**Mentor**: William Brown (wbrown@suse.de - UTC+10:00).

**Skills**: Basic Programming. Nice to have - some knowledge of databases and Rust (but not required). 

**Skill Level**: Beginner to Advanced. Each topic can be scaled up or down to your level, and areas of interest.

**Get started**: 

[1] https://github.com/kanidm/kanidm/blob/master/README.md
[2] https://github.com/kanidm/kanidm/blob/master/CODE_OF_CONDUCT.md
[3] https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/SUMMARY.md 
[4] https://github.com/kanidm/kanidm/blob/master/designs/architecture.rst

**Comment by MihirLuthra** [comment]
Hi,
I am Mihir, final year engineering student.
I was interested in contributing to openSUSE via GSoC.
I am fluent with Rust, C, C++ and Bash.
My exams just ended recently, so got the time to check now only.
Wanted to know if there is still time to pursue this project with a probability to get accepted?

**Comment by abhikjain360** [comment]
Hi!

I'd like to work on this project for GSoC'21. Should I start with contacting the mentor?

**Comment by Firstyear** [comment]
@abhikjain360 Yes - please email me with the details as listed.
