### ISSUE TITLE
Port Jangouts from AngularJS 1.4

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/mentoring#16]
**Description:** Jangouts, a web based videoconferencing tool, is based on AngularJS 1.4. Given that the new version of AngularJS (v2) will be fundamentally different from v1.4, Jangouts should be ported to the new version of AngularJS or to an alternative framework (like the combination of React+Redux). On the other hand, Jangouts was born as a HackWeek project and doesn't have a proper testsuite. So during the transition to the new framework a testsuite should be also developed

**Deliverable:** A new version of Jangouts including a testsuite and based on AngularJS 2 or an alternative framework.

**Mentors:** @ancorgs / ancor@suse.com and @imobach / igonzalezsosa@suse.de

**Skills:** JavaScript

**Skill Level:** medium

 **Getting started:** Pick something from the list of pending [features and bugs](https://github.com/jangouts/jangouts/issues) of Jangouts and try to do something about it.

**Github:** https://github.com/jangouts/jangouts/

**Comment by kalabiyau** [comment]
:+1:

**Comment by harshuopi** [comment]
Hi guys,

I am interesting in this as my GSOC project. And I was wondering why do we need to port it? Will porting to Angular 2 solve many of the issues? If so, which ones?

Thank you.

**Comment by hennevogel** [comment]
Congratulations @magarcia this is your project for GSoC this year! :bouquet:

**Comment by magarcia** [comment]
Thanks @hennevogel
