### ISSUE TITLE
Logging Pipeline Plumber

### ISSUE THREAD

**Issue by paynejacob** [openSUSE/mentoring#164]
**Project Title:** Logging Pipeline Plumber

**Description:** Rancher logging is powered by the Banzai Logging Operator.  The operator is a powerful tool that empowers users to create complex filtering on their logs.  Currently there is no good way to peel back filters and find where the breakdown is.  Sometime users are targeting a particularly elusive log message making the feedback loop for their changes untenable. The goal of this project is to make a simple tool for users to reproduce a log message, determine what filter omitted the message

**Deliverable:** 

- users are able to reproduce log messages from their own applications
- users are able to replicate their log targets with minimal intervention
- the tool is able to identify which step in the log pipeline is excluding the log message
- (optional)  the tool generates a visualization for how logs flow

**Mentor:** Jacob Payne (@paynejacob)

**Skills:** 

need:
- Kubernetes
- helm 
- golang

nice to have:
- Fluentd
- Fluentbit

**Skill Level:** Medium

**Get started:** 
- You can checkout the logging operator here: https://banzaicloud.com/docs/one-eye/logging-operator/
- If you want to see an example setup: https://github.com/paynejacob/rancher-logging-examples
- https://helm.sh/docs/intro/

**Comment by shubhambhardwaj007** [comment]
Hello @paynejacob !!!
I am interested in this project. I have good hands-on experience in k8's and  helm but lack golang knowledge.
Can I go forward in this??

**Comment by paynejacob** [comment]
Hi @shubhambhardwaj007 thanks for taking an interest in this project! This would be a great project to get started with golang on.  1 or 2 golang applications may be required but a majority of the work will be with helm.

**Comment by viveksahu26** [comment]
Hello @paynejacob, This projects meet to mine skills. I know golang, Kubernetes in details and also prepared a chart using Helm.  Seriously, I have no idea about this project. But, if you guide me from today onwards, I will definitely do it.
