### ISSUE TITLE
Improve adding options in Yast security modul

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/mentoring#167]
**Project Title**: Improve adding security options in Yast security modul

**Description**: When trying to add support for an option to the Yast security module (see https://github.com/yast/yast-security/issues/93) it turned out that 26 adjustments would be needed in various places. Since security settings of a system have increasing importance, adding options should be as simple as possible and require changes only in a few places, e.g. in a central configuration file.

**Deliverable**: A working pull request merged into https://github.com/yast/yast-security

**Mentor**: Who is the mentor? @rhabacker Who is the Co-Mentor? still open

**Skills**: Linux, Ruby and shell scripting knowledge

**Skill Level**: Medium
**Get started**: 
1. Get virtual machine or real hardware running with openSUSE distribution
2. Install Yast security module and get familiar with it
3. clone the git repo https://github.com/yast/yast-security and get familiar with the source
4. install rpm package generated from the source mentioned at 3.

**Comment by ddemaio** [comment]
@rhabacker can you send me an email to ddemaio@opensuse.org so I can include you in an email with all the other mentors. Also, how do you want students to contact you about the project? Here? This is the only thing I found to communicate with you.

**Comment by satkaurav** [comment]
Hi @rhabacker!

I am here an undergraduate computer science student and a newbie to open source. 

I want to work to this work so I commented here to let know the community that a student is interested in this project.

I just complete the installation of openSUSE and start reading the YaST project documentation. 

My reason for choosing this project is vast applications of YaST in the openSUSE project. 

Currently I am not good at ruby but I have decent knowledge of C, python and R. I believe that in the next few weeks I gain required knowledge of ruby to start coding. If you suggest a few beginner tasks related to YaST I am happy to do so. 

Best,
Satendra

**Comment by rhabacker** [comment]
Hi @satkaurav, 

thanks for your offer.

> If you suggest a few beginner tasks related to YaST I am happy to do so.

In the Yast security module there is only https://github.com/yast/yast-security/issues/92, which was the reason this project was started. One starting point can be to research which additional options would be useful and to open corresponding issues.

**Comment by rhabacker** [comment]
Hi @satkaurav.

if you want to work on this task you need to register at https://summerofcode.withgoogle.com/ and submit a proposal until April, 13.

**Comment by hmanjhi** [comment]
Hi @rhabacker, Thanks for sharing the information!

Yes I am writing the proposal. Will probably submit it within next two days.

**Comment by rhabacker** [comment]
Since this ticket was opened for GSOC 2021, this is no longer relevant.
