### ISSUE TITLE
Add openEuler as client

### ISSUE THREAD

**Issue by paususe** [openSUSE/mentoring#179]
**Project Title:** Add openEuler as a client

**Description:** [openEuler](https://openeuler.org/en/) is a Linux community distribution and many Chinese OS vendor build their own Linux distribution based on openEuler: EulerOS, EulixOS, TurboLinux, etc. In other words, openEuler is widely used in China so far. This project is about adding openEuler Linux as a new client OS to Uyuni.

**Deliverable:** openEuler LTS is supported with the usual functionality (product mirroring, content management, configuration management, managed as a Salt client via either salt-ssh or salt-minion, monitoring, etc). Not a requirement but even better if you add several "flavors" of openEuler (EulerOS, Eulix, etc).

**Mentor:** @paususe + some other core Uyuni developer

**Skills:** Knowledge openEuler, some Java, some Python, some SQL. We have a template you can follow to enable a new OS.

**Skill Level:** Easy to medium.

**Get started:** See links in https://github.com/openSUSE/mentoring/issues/147

**Comment by dinoallo** [comment]
Hi! @paususe I am interested in this project for [OSPP](https://summer.iscas.ac.cn/#/org/prodetail/210930739?lang=en). I know some Java/Python and have been playing openEuler for a while. I would like to apply for it but I wonder if there are any templates or any requirements(aside from basic information) I need to fill in/provide for proposals?

**Comment by paususe** [comment]
> Hi! @paususe I am interested in this project for [OSPP](https://summer.iscas.ac.cn/#/org/prodetail/210930739?lang=en). I know some Java/Python and have been playing openEuler for a while. I would like to apply for it but I wonder if there are any templates or any requirements(aside from basic information) I need to fill in/provide for proposals?

Hi!

Here you have a starting guide:
https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time

Getting your fork of Uyuni building in your OBS project, as described above, is the first step you will need.

Here you have a full example of how to add a new client operating system. This is for Alibaba Cloud Linux 2 but any other RHEL clone is very similar:
https://github.com/uyuni-project/uyuni/commit/7d3ba0c7f9c914ac71afe2590a096f459437908a

OBS supports both openEuler 20.03 LTS SP1 and 21.03. I suggest you start with 20.03, since in Uyuni we typically support LTS versions first and sometimes (but not often) add also non-LTS:
https://openeuler.org/en/download/

openEuler is a RHEL clone and adding support for it should be fairly straightforward if looking at Alibaba Cloud Linux 2 as an example. The only thing you will be missing is adding an openEuler grain to Salt. Here you can see how I added Alibaba Cloud Linux as a new operating system to Salt while ago:
https://github.com/openSUSE/salt/pull/352
