### ISSUE TITLE
Convert Systems list pages from JSP to ReactJS

### ISSUE THREAD

**Issue by cbosdo** [openSUSE/mentoring#181]
**Project Title:** Convert Systems list pages from JSP to ReactJS

**Description:** Uyuni comes from an old project and still has a lot of legacy JSP pages. A previous Google Summer of Code converted the Virtual Systems list page to ReactJS. This opens the way to the conversion of more of these pages.

Since there is a lot of duplication in these pages, the project would have to start with a reflection about how to aggregate all those pages into one if possible.

**Deliverable:** an Uyuni pull request replacing all the `System List` pages to ReactJS.

**Mentor:** @cbosdo

**Skills:** ReactJS and Java. Hibernate and SQL are a plus.

**Skill Level:** Medium

**Get started:** 

Installing the development environment:

*    https://github.com/uyuni-project/uyuni/wiki/Java-Development-Environment
*    https://github.com/uyuni-project/uyuni/wiki/Frontend-Development-Environment

Installing a test environment:

*    https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time

* Slides on how to get started developing Uyuni: http://bosdonnat.fr/slides/openSUSEAsiaSummit19/#/about
* Uyuni Wiki:
  *  Introduction to Uyuni and systems management (presentation): https://github.com/uyuni-project/uyuni/wiki/Presentations
  *  Uyuni development in no time: https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time
  *  Development pages: https://github.com/uyuni-project/uyuni/wiki/

**Comment by VimukthiRandika1997** [comment]
Hey! @cbosdo,

I am thoroughly interested working on this project. I have sound knowledge in working with REST API, Python, Javascript, ReactJS, Django. Currently I'm looking forward to contribute for an open source project to get an experience in real world development. Please let me know how to get start and further instructions. 

Thanks!

**Comment by cbosdo** [comment]
@VimukthiRandika1997 first get a development instance by reading the documents in the issue description

**Comment by VimukthiRandika1997** [comment]
@cbosdo Yeah!, I have already done that, I am working on it. Thanks

**Comment by VimukthiRandika1997** [comment]
@cbosdo Thank you very much, I will contact you for further instructions!

**Comment by ddemaio** [comment]
Hi @cbosdo   I listed this as a large sized project. About 175 hrs for the student for the medium size and 350 hrs for a large project. Please change it if it isn't correct.

**Comment by cbosdo** [comment]
PR from last year GSoC converting a similar page: https://github.com/uyuni-project/uyuni/pull/4510

**Comment by Ishan-Saini** [comment]
Hey @cbosdo , I have a doubt regarding the development environment setup.
Correct me If I am wrong but as far as I know, there are two ways of setting up the environment. First method makes use of sumaform and the other doesn't. Should I make use of the second method as described here [https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time](https://github.com/uyuni-project/uyuni/wiki/Uyuni-development-in-no-time)?
I am confused about the first steps 😅

**Comment by cbosdo** [comment]
take whichever seems easier to you. The second one without sumaform proved doable to newcomers already

**Comment by cbosdo** [comment]
Done
