### ISSUE TITLE
Build Uyuni Client Tools packages for Debian with debbuild

### ISSUE THREAD

**Issue by vzhestkov** [openSUSE/mentoring#183]
**Project Title:** Build Uyuni Client Tools pakcages for Debian with debbuild

**Description:** Now most of the client tools packages for Debian based distros are building with native method of building packages for Debian. Switching to `debbuild` will help to limit the nuber of tha packages in OBS to maintain by creating single source for each package for all of the distros.

**Deliverable:** an OBS project with packages building with `debbuild`

**Mentor:** @vzhestkov

**Skills:** Basic OBS, rpm packages building (spec files and macros).

**Skill Level:** Medium

**Get started:**

Project configuration to use `debbuild`: https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.prjconfig.html#vl.prjconfig.keywords

GitHub project: https://github.com/debbuild/debbuild

**Comment by ddemaio** [comment]
@vzhestkov should I keep this open?
