### ISSUE TITLE
A new Test Framework for Salt

### ISSUE THREAD

**Issue by agraul** [openSUSE/mentoring#184]
**Project Title:** A new Test Framework for Salt

**Description:**  We maintain our own version of [Salt](https://github.com/openSUSE/salt), which differs in some ways from the upstream [Salt project](https://github.com/saltstack/salt). We have been using a test framework called [Salt Toaster](https://github.com/openSUSE/salt-toaster) to test our Salt version on different operating systems, e.g. openSUSE Leap and Ubuntu. While Salt Toaster handles many features we want, it is not in a well-maintained state which makes it hard to adjust and enhance.
This project is all about developing a new testing framework with the aim to eventually replace Salt Toaster.

**Deliverable:** A branch in [openSUSE/salt-toaster](https://github.com/openSUSE/salt-toaster) with the new testing framework. The code can be written in Python, Go, and/or Rust. The new test framework does not need to be production-ready, but rather a base to built upon.

**Mentor:** @agraul, @meaksh (backup)

**Skills:** Knowledge of Python and [pytest](https://docs.pytest.org/en/7.0.x/) is required. 

**Skill Level:**  Hard

**Get started:** 
- Setup [Salt for development](https://docs.saltproject.io/en/latest/topics/development/hacking.html#installing-for-development)
- Run Salt's test suite with the help of https://docs.saltproject.io/en/latest/topics/tutorials/writing_tests.html#tutorial-salt-testing and https://docs.saltproject.io/en/latest/topics/development/tests/index.html
- Take a look [Salt Toaster](https://github.com/openSUSE/salt-toaster#readme)
- Read through https://github.com/openSUSE/salt-toaster/wiki/Salt-Toaster's-Future

**Comment by ddemaio** [comment]
Listing this project under Uyuni since its related to salt @cbosdo .
