### ISSUE TITLE
Modernize and streamline the Travel Support Program Workflow

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/mentoring#185]
Project Title: Modernize and streamline the Travel Support Program Workflow

Description: Update the Travel Support Program to a more modern appearance and workflow, so it is easier to navigate and use for both users and admins.

Deliverable: A working Travel Support Program website that is functional for users and admins with a modern UI/UX.

Mentor: TBD

Skills: Knowledge of Ruby, html, css and JavaScript.

Skill Level: Medium

Get started:
Review of Travel Support Program [code](https://github.com/openSUSE/travel-support-program)
Test the functionality of <https://tsp.opensuse.org>

**Comment by ddemaio** [comment]
@hellcp did you want me to list this as a GSoC project? Would you be willing to mentor and offer some guidance. Or do you think I should close it?

**Comment by hellcp** [comment]
Before doing any modernizing we would have to do a bunch of updates with more current technologies, so TSP is not currently ready for this project either way
