### ISSUE TITLE
Porting PRoot to Various Architectures

### ISSUE THREAD

**Issue by oxr463** [openSUSE/mentoring#187]
**Project Title:** Porting PRoot to Various Architectures

**Description:** Both implementations of PRoot currently only support x86, x86_64, arm, and aarch64. We would like to expand the supported architectures to include s390x, mips, and powerpc. 

**Deliverable:** compiled static binaries for each architecture

**Mentor:** @oxr463 

**Skills:** c, rust, Linux, ptrace, syscalls, seccomp

**Skill Level:** Hard

**Get started:** See: https://github.com/proot-me/proot/issues/264, https://github.com/proot-me/proot/issues/324, https://github.com/proot-me/proot/issues/322

**Comment by Kreijstal** [comment]
Tfw I own a riscv device and this is not even on the list :(

**Comment by zv-io** [comment]
@ddemaio is this completed somewhere? I'm interested in either doing, or using, the work required to port PRoot to PowerPC (and possibly others).

**Comment by ddemaio** [comment]
Hi @zv-io. This wasn't completed, so I closed and removed it from the frontend of 101.opensuse.org. You could ask @oxr463 and see if they are interested in mentoring for a future Google Summer of Code or something.
