### ISSUE TITLE
Accessibility improvements for Uyuni

### ISSUE THREAD

**Issue by deneb-alpha** [openSUSE/mentoring#190]
**Project Title:** Accessibility improvements for Uyuni

**Description:** The goal of this project is to analyse, track, document and solve accessibility issues in [Uyuni](https://www.uyuni-project.org/), increasing the accessibility support of this configuration and infrastructure management tool.

**Deliverable:** 
- Report the accessibility issues highlighted by [WebAIM](https://wave.webaim.org/)
- Have a dedicated branch for the accessibility fixes provided
- Submit pull requests with the fixes for the issues agreed
- Document the common mistakes highlighted and fixed
- Document common best-practice to be followed while contributing to Uyuni  

**Mentors:** 
* @cbbayburt
* @deneb-alpha 

**Skills:** 
- Accessibility basics
- Java
- JavaScript
- XML

**Skill Level:** Medium

**Get started:** 
- Have an instance of Uyuni. 
- Install the https://wave.webaim.org/ web-browser extension. 
- Starting from the login page use WebAIM and report the highlighted problems.
- Classify the problems with labels: `errors` `contrast` `features` `structural` `aria` 
- Discuss with the mentor(s) the priorities of the issues
- ...have fun! ;)

**Comment by aaryahjolia** [comment]
Hello, Is there any mentor assigned to this project?

**Comment by deneb-alpha** [comment]
> Hello, Is there any mentor assigned to this project?

Hello @aaryahjolia, the list of mentors for this project has been just updated. 

Is there anything else we can support you with?

**Comment by ffshreyansh** [comment]
Hey @deneb-alpha , I am a front dev using react and jquery mostly, have some knowledge on nodejs as well. Can i be helpful for this project or for this particular task. I would love to contribute If I can be of any help.

**Comment by deneb-alpha** [comment]
> Hey @deneb-alpha , I am a front dev using react and jquery mostly, have some knowledge on nodejs as well. Can i be helpful for this project or for this particular task. I would love to contribute If I can be of any help.

Hello!
Do you have any prior experience with accessibility? Or, have you tried to look at how to setup Uyuni and it's requirements?

**Comment by ffshreyansh** [comment]
@deneb-alpha I am not clear what exactly accessibility goes here. I mean it's related to user experience or something if you pls elaborate that would be very helpful. 
And yeah I read Uyuni's documentation.
I am not clear If I may be able to contribute through the front end.?

**Comment by deneb-alpha** [comment]
Hello @ffshreyansh 

> @deneb-alpha I am not clear what exactly accessibility goes here. I mean it's related to user experience or something if you pls elaborate that would be very helpful. 

Accessibility isn't just limited to improved user experience . You can find a comprehensive documentation at https://www.w3.org/WAI/fundamentals/.

For this project, the general idea is also to  focus on the Web Content Accessibility Guidelines  (WCAG) but of course, according to  the mentee's experience  we could re-calibrate the project a bit more and match reality.

The https://wave.webaim.org/ page is also providing some  more details too. 

> And yeah I read Uyuni's documentation. I am not clear If I may be able to contribute through the front end.?

We will probably work just on the front end part, but in general some Java/JSP knowledge is appreciated too.

**Comment by Rakielle** [comment]
Hello @cbbayburt and @deneb-alpha,

I'm interested in contributing to this project. I am currently following the steps listed above to get started.
I've installed openSUSE leap, Uyuni, and wave extension. I want to use the wave tool to investigate the accessibility issues in Uyuni.

But, I'm not clear on how I should report the issues.

**Comment by deneb-alpha** [comment]
> Hello @cbbayburt and @deneb-alpha,
> 
> I'm interested in contributing to this project. I am currently following the steps listed above to get started.
> I've installed openSUSE leap, Uyuni, and wave extension. I want to use the wave tool to investigate the accessibility issues in Uyuni.
> 
> But, I'm not clear on how I should report the issues.

Hello @Rakielle !
Please, if you already have issues to report, do it in the uyuni organization and add a link to this issue.

**Comment by cbosdo** [comment]
@ddemaio this one can be closed too

**Comment by deneb-alpha** [comment]
@ddemaio please, close this project
