### ISSUE TITLE
Define a workflow how to collect mentoring projects

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#2]
The idea is for this repository to hold the web site (gh-pgaes) and to manage mentoring projects in this repos issues. How?

**Comment by ChrisBr** [comment]
I'd propose 

1. The mentor adds a new issue

  ### Title: Title of the mentoring project
  ### Description:
  * Description
  * Deliverable
  * Mentor (additional assign the issue to the primary mentor)
  * Skills
  * Skill Level
  * Byte Sized tasks for students to get involved (e.g. GitHub issues, low hanging fruits, junior jobs)
  * GiHub repository
  * Resources to get started (tutorials, links)

2. Label the issue
  * Project: e.g. OSEM, Machinery etc (to link from the gh page)
  * Program: e.g. GSoC, RGSoC, Hackweek
  * Optional: We could also label the skill (e.g. Ruby, web development) and skill level (eg. Easy, Medium, Hard) but than it could start getting confusing with too much labels...

With the labels we can link from the gh page to the issues e.g. https://github.com/openSUSE/mentoring/issues?q=is%3Aopen+is%3Aissue+label%3AGSoC for all open GSoC projects.

**Comment by hennevogel** [comment]
So the issue exists and describes the mentoring project and it's data. What next? How do people 'apply' for it? How are students selected?

**Comment by hennevogel** [comment]
Github labels have the problem that they are exclusive. You can't list all OSEM projects for GSoC. There is no `AND`...

**Comment by hennevogel** [comment]
Ah no it's `OR` that doesn't exist...

**Comment by ChrisBr** [comment]
Interested students would write in the issue that they're interested and can start to fix the "Byte Sized tasks for students to get involved" or do some research! Detailed discussion can be done via email like before.

What RGSoC for instance does is, that they label the issue with "Max number of applicants reached" if for instance 3 or four teams/students already have applied for the project. But I'm not sure if we really need this ...

Depending of the program the students also have to submit the "application" to a different platform (e.g. GSoC google-melange). AFAIK the selection process will be handled there but I was never involved in the selection process. That's something @hennevogel and @cornelius have more experience ...

**Comment by ChrisBr** [comment]
@hennevogel we don't need ``or``, ``and`` should be enough (``GSoC and OSEM`` or ``GSoC``)

**Comment by hennevogel** [comment]
Yeah with external programs the selection wouldn't happen at all here in this repo. Hm maybe we don't want to handle selection at all in here?

**Comment by ChrisBr** [comment]
@hennevogel yep, and most of all the selection is (mostly) done by the mentor! Only the mentor can say which applicants fits the best ...

**Comment by hennevogel** [comment]
Okay but how do students know what is taken? Re-assign from Mentor to Student?

**Comment by ChrisBr** [comment]
You mean which project isn't available anymore?

I don't think assign to a student isn't sufficient because how should anyone new to the project know who is a mentor and who is a student! I'd either also cover this with a label (easy search but to many labels) or just close the issue (search is also easy) or write a comment (search hard and you have to open the issue). I'd go for closing the issue because when it's taken you can continue the conversation in the corresponding issue/repository of the project.

**Comment by ChrisBr** [comment]
Described in 
http://opensuse.github.io/mentoring/mentor/ and
https://github.com/openSUSE/mentoring/blob/gh-pages/templates/mentored_project.md

I guess we can close this one? @hennevogel

**Comment by hennevogel** [comment]
Yes we can!
