### ISSUE TITLE
Editing Kerberos services with Yast2

### ISSUE THREAD

**Issue by rhabacker** [openSUSE/mentoring#200]
**Project title:** Editing Kerberos services with Yast2

**Description:** The configuration tool Yast2 supports the creation of Kerberos services (see below), but not the further editing, which is currently only possible in a cumbersome way via the command line and editing files (https://doc.opensuse.org/documentation/leap/security/html/book-security/cha-security-kerberos.html). A basic functionality for editing Kerberos services should be added to Yast2 with this project.

**Deliverable:** Upon completion of the project, basic editing of Kerberos services should be possible with Yast2. 

**Mentor:** Ralf Habacker - Co-Mentor position is still open, applications welcome.

**Skills:** What knowledge is needed? ruby, python, bash, systemd, kerberos

**Skill level:** estimated between light and medium

**Project size:** `Medium project (175 hours)` , extendable to `Large project (350 hours)`

**Get started:**
- Examine the existing Kerberos service creation module for errors or opportunities for improvement and attempt to submit appropriate corrections/changes
- Examine what is commonly customized when editing a Kerberos service to determine potential project scope.
- A good source to understand the structure of YaST2 and the module to be extended are the sources of the corresponding package `yast-auth-server`.

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/602903/217375097-c40e188b-5a21-40bd-89d8-07a083183d1e.png)
![grafik](https://user-images.githubusercontent.com/602903/217374965-98d9e9c4-b36f-4888-8563-476dfe7b4518.png)

**Comment by ddemaio** [comment]
Hi @rhabacker. It might show you in the GSoC 2022. Could you log in to g.co/gsoc and click on the 2023 bar which will show the 2023 Program Rules and Org Member agreement that they need to read and agree to.  The important thing is that you acknowledge the agreement.

**Comment by rhabacker** [comment]
> Hi @rhabacker. It might show you in the GSoC 2022.

I spoke with GSoC support about this, and they informed me that since I was previously registered, a GSoC org admin would need to add me as a mentor.
