### ISSUE TITLE
Improve accessibility of the openQA web frontend

### ISSUE THREAD

**Issue by Martchus** [openSUSE/mentoring#202]
**Project Title:** Improve accessibility of the openQA web frontend

**Description:**
[openQA](https://open.qa/) is an automated test tool for operating systems and the engine at the heart of openSUSE's automated testing initiative. It provides already several backends that allows testing an O.S. on a variety of architectures and scenarios including baremetal and different kinds of virtualized environment.

The web frontend of the tool (checkout the public instance [o3](https://openqa.opensuse.org/) for an example) does not provide good accessibility according modern standards. The main known issues are:

* The default color palette does not provide good contrast and there is no alternative color palette with better contrasts.
* The dark color palette has only been introduced recently and still has issues impairing readability and overall appearance.¹
* The needle editor (and possibly other pages) are not color-blindness friendly as they use colors exclusively to convey certain information (e.g. the type of the needle).²
* Whether the web pages work well on screen readers has never been tested. We should identify what we can improve. Maybe there are small tweaks that make a big difference which we can apply. (Since openQA is a very visual tool it makes likely no sense to invest a lot of effort in that point, though.)

This list is not exhaustive. It would be generally a good idea to research the current best practices regarding accessibility on web pages and implement applicable ones.

**Deliverable:** Code is merged with the necessary tests to prove each improvement. Documentation has been updated.

**Mentor:** @okurz, @kalikiana

**Skills:** HTML, CSS, JavaScript and Perl/Mojolicious for the server-side (you can learn Perl on-the-fly if you're familiar with web development in general), general knowledge about software development in the GNU/Linux ecosystem (setting up a development environment, using Git and the command-line)

**Skill Level:** Medium

**Get started:**

* Engage with the development team! We hang out in https://app.element.io/#/room/#openqa:opensuse.org and #opensuse-factory on Libera.Chat!
* Start forking the [openQA](https://github.com/os-autoinst/openQA) and the [os-autoinst](https://github.com/os-autoinst/os-autoinst) repositories
*  General hints and advice for good project proposals:
    * https://google.github.io/gsocguides/student/writing-a-proposal
    * https://hackernoon.com/7-things-you-need-to-know-to-ace-your-gsoc-proposal-92ff7ef23f5a
    * https://medium.com/oppia-org/things-i-learned-from-reviewing-gsoc-proposals-154707cdcca5

---
¹ see https://progress.opensuse.org/issues/119032 and sub tickets like https://progress.opensuse.org/issues/119371 and https://progress.opensuse.org/issues/119374
² see https://progress.opensuse.org/issues/125138

**Comment by Martchus** [comment]
I'm not sure whether it deserves the "Large Sized Project" label. I haven't add a time estimation as it would likely very much depend on the skills of the developer.

**Comment by himanshu007-creator** [comment]
Hi!
i would love to work on this project as a GSOC'23 student!

**Comment by OfficialAkashKumar** [comment]
Hello, I came across this project in Gsoc 2023 under openSUSE and it seems quite interesting to me. I have expertise in HTML, CSS, and javascript and intermediate knowledge in perl. 

I would like to work on this project.

**Comment by okurz** [comment]
you can now officially apply and send in applications for this and other GSOC projects over https://summerofcode.withgoogle.com/

**Comment by foursixnine** [comment]
Some of the submitted proposals are missing critical information, like a timeline, giving a rough idea of how or any research into the topic or what the work is (seemingly) beyond the description stated on this topic.

For reference, here are some proposals sent before to other projects: https://github.com/Google-Summer-of-Code-Archive/gsoc-proposals-archive/tree/main/2021

**Comment by Martchus** [comment]
Do you want me to add something in particular? I was mainly following what I've seen in other proposals here. The PDFs you've been linking are often multiple pages long (I've just briefly checked a few) and contain many more details. I'm not sure I can provide that for this task.

**Comment by foursixnine** [comment]
> Do you want me to add something in particular?

I think from the description of this issue all is good, I' m referring more to some of the already submitted proposals for this particular topic.

**Comment by okurz** [comment]
The project will be covered as part of GSOC 2023. @Martchus I suggest you close the issue.
