### ISSUE TITLE
Home page - refactor accordion to bootstrap specification

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#212]
### Accessibility Issue - accordian component
**Page**
[Home/landing page](https://www.uyuni-project.org/)
Severity: Error

**Description** 
The Bootstrap (v4.2.1) accordion component has several issues that can resolved by following the implementation provided on the [Bootstrap](https://getbootstrap.com/docs/4.2/components/collapse/#accordion-example) website.

Among them are:
- 6 broken references marked as aria-labelledby that do not point to a target reference. ARIA labels and descriptions will not be presented if the element referenced does not exist in the page.
- 2 heading levels are skipped, meaning they aren't accessible by keyboard tabbing

**Proposed Solution**
- Solution: Follow the Bootstrap implementation ensuring that the element referenced in the aria-labelledby or aria-describedby attribute value is present within the page and presents a proper label or description.

**Additional Notes**
- There are other issues within the accordion, but thats for another issue
- [1.3.1 Info and Relationships (Level A)](https://webaim.org/standards/wcag/checklist#sc1.3.1)
- [4.1.2 Name, Role, Value (Level A)](https://webaim.org/standards/wcag/checklist#sc4.1.2)

**Screenshot**
![Screen Shot 2024-05-08 at 11 18 50 pm](https://github.com/openSUSE/mentoring/assets/997506/3ddd4845-9809-4195-b929-77fa86bcda63)

**Comment by deneb-alpha** [comment]
moving to https://github.com/uyuni-project/uyuni-project.github.io/issues/108
