### ISSUE TITLE
Update year in footer

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#214]
### Accessibility/Responsive Issue
**Page**  
[Home/landing page](https://www.uyuni-project.org/)

**Description**  
The year is out of date in the footer.
This is not an accessibility or responsive issue - but an update

**Proposed Solution**  
- Solution 1: Bump year from 2023 to 2024

**Screenshot**  
![Screen Shot 2024-05-09 at 1 30 43 am](https://github.com/openSUSE/mentoring/assets/997506/a654a765-e68e-43c1-99e4-97da6561950c)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/110
