### ISSUE TITLE
Stable Version page - Broken same-page link

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#216]
### Accessibility Issue
**Page**  
[Stable Version page](https://www.uyuni-project.org/pages/stable-version.html)
Severity: Warning

**Description**  
A link to jump to another position within the page assists users in navigating the web page, but only if the link target exists.
A user might be confused when the browser page does not change. In-page links should generally be presented so it is visually and/or contextually apparent that they are in-page link

**Proposed Solution**  
- Solution 1: Create a permalink that is not a heading with an appropriate aria-label (thus giving it the target a reference)

**Screenshot**  
![Screen Shot 2024-05-10 at 1 40 33 am](https://github.com/openSUSE/mentoring/assets/997506/1d25dee5-cec3-4c4d-a2f2-b4be8c446e6c)

**Related Issue**
[221](https://github.com/openSUSE/mentoring/issues/221)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/112
