### ISSUE TITLE
Contact page - 36 low contrast warnings

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#217]
### Accessibility/Responsive Issue
**Page**  
[Contact page](https://www.uyuni-project.org/pages/contact.html)

**Description**  
There are 36 low contrast warning for the page.

Very low contrast between text and background colors. These are all CSS styles effecting links in the page body.
Adequate contrast of text is necessary for all users, especially users with low vision.

The link text that is present that has a contrast ratio less than 4.5:1, or large text (larger than 18 point or 14 point bold) has a contrast ratio less than 3:1. 
WCAG requires that page elements have both foreground AND background colors defined (or inherited) that provide sufficient contrast. 
When text is presented over a background image, the text must have a background color defined (typically in CSS) that provides adequate text contrast when the background image is disabled or unavailable.

WCAG Level AA requires a contrast ratio of at least 1.4.3 Contrast (Minimum)
WCAG Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.

**Proposed Solution**  
- Solution 1: Increase the contrast between the foreground (text) color and the background color. Large text (larger than 18 point or 14 point bold) does not require as much contrast as smaller text.

**Additional Notes**  
-  [WCAG Level AAA](https://www.w3.org/TR/WCAG22/#contrast-enhanced) requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
- [1.4.3 Contrast (Minimum) (Level AA)](https://webaim.org/standards/wcag/checklist#sc1.4.3)

**Related issue**  
[222](https://github.com/openSUSE/mentoring/issues/222)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/113
