### ISSUE TITLE
Contact page - Skipped heading levels

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#218]
### Accessibility/Responsive Issue
**Page**  
[Contact page](https://www.uyuni-project.org/pages/contact.html)
Severity: Alert
Impacts: Body content 

**Description**  
Heading levels are skipped from H1 to H4, there is no intermediate H2 or H3.

Headings provide document structure and facilitate keyboard navigation by users of assistive technology. These users may be confused or experience difficulty navigating when heading levels are skipped.

**Proposed Solution**  
- Solution 1: Restructure the document headings to ensure that heading levels are not skipped.

**Additional Notes**  
- [1.3.1 Info and Relationships (Level A)](https://webaim.org/standards/wcag/checklist#sc1.3.1)
- [2.4.6 Headings and Labels (Level AA)](https://webaim.org/standards/wcag/checklist#sc2.4.6)
- [G141: Organizing a page using headings](https://www.w3.org/WAI/WCAG22/Techniques/general/G141)

**Screenshot**  
![Screen Shot 2024-05-10 at 1 40 33 am](https://github.com/openSUSE/mentoring/assets/997506/f6d949d6-e821-494a-a38e-a841c75bb109)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/116
