### ISSUE TITLE
FAQ - remove unordered list items (styles)

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#219]
### Accessibility/Responsive Issue
**Page**  
[FAQ page](https://www.uyuni-project.org/pages/faq.html)
Type: Stylistic

**Description**  
On the FAQ page list items show bullet points that are 'off' - stylistically it looks offsetting

**Proposed Solution**  
- Solution 1: Use CSS to remove bullet points
- Solution 2: Use CSS to align bullet point to the question being addressed

**Screenshot**  
![Screen Shot 2024-05-15 at 1 04 37 am](https://github.com/openSUSE/mentoring/assets/997506/c93b0b11-3126-4ef2-9445-6955e8db11b4)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/118
