### ISSUE TITLE
News page - Contrast errors

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#222]
### Accessibility Issue
**Page**  
[News page](https://www.uyuni-project.org/pages/news.html)
Severity: Error

**Description**  
There are 142 low contrast errors - links mostly.
These can be fixed by ([#217](https://github.com/openSUSE/mentoring/issues/217))

There is very low contrast between link text and background colors.
Text is present that has a contrast ratio less than 4.5:1, or large text (larger than 18 point or 14 point bold) has a contrast ratio less than 3:1. WCAG requires that page elements have both foreground AND background colors defined (or inherited) that provide sufficient contrast. When text is presented over a background image, the text must have a background color defined (typically in CSS) that provides adequate text contrast when the background image is disabled or unavailable.

**Proposed Solution**  
- Solution: The visual presentation of text/background has a contrast ratio of at least 4.5:1 (minimum recommendation AA)

**Additional Notes**  
-  [WCAG Level AAA](https://www.w3.org/TR/WCAG22/#contrast-enhanced) requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.
- [WCAG Level AA - Minimum](https://www.w3.org/TR/WCAG22/#contrast-minimum)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/123
