### ISSUE TITLE
Stable version page - code tag contrast error

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#223]
### Accessibility Issue
**Page**  
[Stable version page](https://www.uyuni-project.org/pages/stable-version.html)
Severity: Error

**Description**  
The CSS on the code tags have a very low contrast rating (3.5:11) between text and background colors.
Text is present that has a contrast ratio less than 4.5:1. WCAG requires that page elements have both foreground AND background colors defined (or inherited) that provide sufficient contrast.

**Proposed Solution**  
Solution: Increase contrast ratio to meet the WCAG Level AA minimum.

**Additional Notes**  
- [1.4.3 Contrast (Minimum) (Level AA)](https://webaim.org/standards/wcag/checklist#sc1.4.3)
- [1.4.6 Contrast (Enhanced) (Level AAA)](https://www.w3.org/TR/WCAG22/#contrast-enhanced)

**Screenshot**  
![Screen Shot 2024-05-22 at 2 01 09 am](https://github.com/openSUSE/mentoring/assets/997506/4818e860-b5f0-43a0-aab3-d11cccdb7b08)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/121
