### ISSUE TITLE
Stable version page - Link to PDF document

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#224]
### Accessibility Issue
**Page**  
[Stable version page](https://www.uyuni-project.org/pages/stable-version.html)
Severity: Warning

**Description**  
Links to a PDF document are present.
Unless authored with accessibility in mind, PDF documents often have accessibility issues. Additionally, PDF documents are typically viewed using a separate application or plug-in, and can thus cause confusion and navigation difficulties.

Because PDF documents may have limitations in accessibility (particularly for complex content) and require a separate program, HTML content should often be used in place of or in addition to the PDF document.

**Proposed Solution**  
Solution: Ensure the PDF document is natively accessible. Additionally, inform the user that the link will open a PDF document by adding a more informative descriptive link text. This can help users understand what to expect when clicking the link.
An example of link text being: "Quick Start Guide (PDF)".

**Screenshot**
![Screen Shot 2024-05-22 at 2 24 47 am](https://github.com/openSUSE/mentoring/assets/997506/024ea231-0b1d-4e38-b6f1-823a9d6011b9)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/120
