### ISSUE TITLE
Stable version page - 7 redundant links

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#227]
### Accessibility
**Page**  
[Stable version page](https://www.uyuni-project.org/pages/stable-version.html)  
Severity: Warning (low)

**Description**  
Adjacent links go to the same URL. When adjacent links go to the same location (such as a linked product image and an adjacent linked product name that go to the same product page) this results in additional navigation and repetition for keyboard and screen reader users that could cause confusion.

**Notes**
The spec specifies that "The purpose of each link can be determined from the link text alone, or from the link text and its context" is sufficient - so I've noted it as 'low' priority as each link text is different and that WAVE flags it as an 'alert' only.

**Proposed Solution**  
Solution 1: Adjacent link text can be grouped together if they both point to the same resource, eg. 
[openSUSE Leap 15.* (x86_64, aarch64) AND openSUSE Leap Micro 5.* (x86_64, aarch64)](https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/)
Solution 2: Further clarify the purpose of the link element using a title attribute.

**Additional Notes**  
- [2.4.4 Link Purpose (In Context) (Level A)](https://webaim.org/standards/wcag/checklist#sc2.4.4)
- [Supplementing link text with the title attribute](https://www.w3.org/WAI/WCAG22/Techniques/html/H33.html)

**Related**  
![Screen Shot 2024-05-28 at 12 59 05 am](https://github.com/openSUSE/mentoring/assets/997506/4a957abc-012e-4962-9c66-fa046b18bc67)

**Related issue**  
[226](https://github.com/openSUSE/mentoring/issues/226)

**Comment by deneb-alpha** [comment]
moved to https://github.com/uyuni-project/uyuni-project.github.io/issues/109
