### ISSUE TITLE
Dockerize Open Source Event Manager

### ISSUE THREAD

**Issue by kalabiyau** [openSUSE/mentoring#23]
**Project Title:** Dockerize Open Source Event Manager

**Description:** To be able to deploy OSEM even faster to give it a try locally with 0 effort we would like to dockerize app with sattelite containers via docker-compose

**Deliverable:** executable script + related documentation which will spin up required containers and seed data to get started

**Mentor:** Artem Chernikov @kalabiyau / achernikov@suse.com

**Skills:** Rails, Ruby, Linux, Docker as a plus

**Skill Level:** Medium

**Get started:** Take your time and pick something from [OSEM Junior Issues](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior)

**Comment by kalabiyau** [comment]
@ChrisBr please assign me and set label as I do not have rights :)

**Comment by nanduni-nin** [comment]
Dear Sir,
I would like to contribute to this project since I am very familiar with Docker. I assume that his project requires me to create a Dockerfile to start and run the app. Am I right? Can you please explain me more on this project?

Thank you.

**Comment by ChrisBr** [comment]
@kalabiyau ping!

**Comment by nanduni-nin** [comment]
@kalabiyau  I would like to contribute to this project since I am very familiar with Docker. I assume that his project requires me to create a Dockerfile to start and run the app. Am I right? Can you please explain me more on this project?

**Comment by kalabiyau** [comment]
@nanduni-nin generally you are right, but also that task would not just mean a Dockerfile, but also the "whole story". We think that should be possible to spin-up OSEM in one command involving Docker. For local testing and evaluation. But also we should have a whole scenario on how to do that in production.

**Comment by ChrisBr** [comment]
@kalabiyau is this one still valid? If yes please open a new issue! Thanks!
