### ISSUE TITLE
Patches page - Possible list

### ISSUE THREAD

**Issue by adritek** [openSUSE/mentoring#230]
### Accessibility Issue
**Page**  
[Patches page](https://www.uyuni-project.org/pages/patches.html)  
Severity: Alert
Impacts: Body content

**Description**  
Text is structured like a list but lacks proper list semantics.

Ordered and unordered lists, when properly defined, provide useful information to users, such as an indication of the list type and number of list items. When text alone is used to present list structures and content, these benefits are lost.

**Proposed Solution**  
Solution: If list content is presented, use \<ul> or \<ol> markup to semantically define the list.

**Additional Notes**  
- [1.3.1 Info and Relationships (Level A)](https://webaim.org/standards/wcag/checklist#sc1.3.1)

**Screenshot**  
![Screen Shot 2024-05-28 at 1 58 25 am](https://github.com/openSUSE/mentoring/assets/997506/ce62f6bb-bd7b-43a3-994f-14c8b65d873f)

**Comment by deneb-alpha** [comment]
moved to the right organization and project -> https://github.com/uyuni-project/uyuni-project.github.io/issues/107
