### ISSUE TITLE
 Implement ticket payment feature for OSEM

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#24]
**Description:** The [Open Source Event Manager](http://osem.io) is an event management app tailored to Free Software Conferences, it is developed in the [Ruby on Rails](http://rubyonrails.org/) web framework. OSEM already has a feature to sell conference tickets. At the moment the user has to buy the ticket online and pay on arrival at the conference. We would like to have a way to purchase and pay online.

**Deliverable:** Workflow to support online payment of conference tickets.

**Mentors:** @chrisbr @hennevogel @differentreality 

**Skills:** Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Medium

 **Getting started:** Pick one of the [Junior](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) labeled issues and get in touch with the mentors. Furthermore have a look at the [Stripe](https://stripe.com/docs) and [Active Merchant](http://activemerchant.org/) APIs.

**Github:** https://github.com/openSUSE/osem

**Comment by jiteshjha** [comment]
Hello! I would like to take on this project for GSOC 2016. How do I proceed? Thanks!

**Comment by ChrisBr** [comment]
Hi @jiteshjha,

nice to see that you're interested in this project.

1) You should first start forking and checking out OSEM. Note that we have [vagrant](https://github.com/openSUSE/osem/blob/master/INSTALL.md) to make this easier for you!
2) Try to run the testsuite locally
3) Pick some [JuniorJob](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) and try to fix it.

**Comment by arun1595** [comment]
Hello. I would like to work on this project for GSoC '16. I have forked the repository and I have OSEM running on VM using Vagrant. Trying to solve a junior job. Thanks!

**Comment by rishabhs95** [comment]
Hi. I am Rishabh Saxena, a second year undergraduate currently studying in BIT Mesra, India and  I have experience in web development and am very interested to work on this project with GSoC '16 and further. I have forked the repo and will be trying to get some junior job done to get acquainted with the codebase. Can you guide me with some additional things I need to take care of?

**Comment by ChrisBr** [comment]
@arun1595 @rishabhs95 Great! As stated in my previous comment, your first steps should be to setup your development environment, we recommend using [vagrant](https://github.com/openSUSE/osem/blob/master/INSTALL.md) and try to fix some [junior jobs](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior). 

Most of our team you can find in [IRC](http://www.irchelp.org/irchelp/irctutorial.html), #osem @ freenode. 

For GSoC you also need to write a proposal, we recommend to stick to this [manual](http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/).

If you have more questions, join us on IRC or just comment in this issue!

**Comment by AlexMex90** [comment]
I have Ruby on Rails running under Ubuntu installed with rvm would this configuration work to contribute?

**Comment by ChrisBr** [comment]
@AlexMex90 any setup with which you can run, code and test OSEM is fine. However, we can't support any system therefore we have a [Vagrant](https://github.com/openSUSE/osem/blob/master/INSTALL.md) box which you can use.

Just start by fixing some of our [junior jobs](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior).

**Comment by rishabhs95** [comment]
@AlexMex90 you can run osem using vagrant(preferred), but if you want to run it on your configuration just make sure to execute the commands which vagrant executes to setup its environment, which you can find in your main directory

**Comment by AlexMex90** [comment]
when I run `vagrant up` 

`vm:
* The box 'opensuse/openSUSE-42.1-x86_64' could not be found.
`
do I have to manually create the box in virtualbox? or should it be automatic?

**Comment by rishabhs95** [comment]
@AlexMex90 have you tried setting up vagrant by following this [guide](https://github.com/openSUSE/osem/blob/master/INSTALL.md).  vagrant sets it up for you automatically if you follow the guide properly.

**Comment by AlexMex90** [comment]
@rishabhs95 yeah, I followed those steps, but no avail. Do I need a particular version of vagrant and/or virtualbox? I am running Ubuntu 14.04 (Bay Trail kernel bug prevents me from installing something with a kernel newer than 3.16)

**Comment by ChrisBr** [comment]
@AlexMex90 Try to add it manually:

``
vagrant box add opensuse/openSUSE-42.1-x86_64 https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64/versions/1.0.0/vagrant/providers/virtualbox.box
``

**Comment by AlexMex90** [comment]
Is the URL correct? it returns a 404.

**Comment by rishabhs95** [comment]
vagrant init opensuse/openSUSE-42.1-x86_64; vagrant up --provider virtualbox
this works for me. check if it does for you @AlexMex90

**Comment by AlexMex90** [comment]
This is what I get.

```
alex@dellia:~/Documents/Projects/Ruby/osem$ vagrant init opensuse/openSUSE-42.1-x86_64; vagrant up --provider virtualbox
`Vagrantfile` already exists in this directory. Remove it before
running `vagrant init`.
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'opensuse/openSUSE-42.1-x86_64' could not be found.

```

**Comment by AlexMex90** [comment]
I attempted this, I got this:

```
alex@dellia:~/Documents/Projects/Ruby/osem$ vagrant box add opensuse/openSUSE-42.1-x86_64 https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64
Downloading box from URL: https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64
Extracting box...e: 0/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

```

**Comment by AlexMex90** [comment]
This worked:

`vagrant box add opensuse/openSUSE-42.1-x86_64 http://downloadcontent.opensuse.org/vagrant/openSUSE-42.1-virtualbox-x86_64-1.0.0.box`

**Comment by ChrisBr** [comment]
@AlexMex90 the error message

``
`Vagrantfile` already exists in this directory
``

is correct because we already have a [Vagrantfile](https://github.com/openSUSE/osem/blob/master/Vagrantfile).

Does it work now for you or do you still need help?

**Comment by AlexMex90** [comment]
@ChrisBr  Thank you for your answer! It worked with the command I mentioned in my lest post, It worked around 2 a.m. so I haven't had the chance to test anything else, but I was able to run OSEM.

**Comment by awasum** [comment]
Hello @ChrisBr and @hennevogel ,

My name is Awasum Yannick. i'm a student in the university of buea in cameroon.
I am interest the OSEM project and have already setup my development environment. I am working on my proposal while studying the code base and already fixing common bugs and issues involved in setting up developer environment and basic responsive UI design. How do i submit my proposal to be corrected before uploading to Gsoc??

**Comment by ChrisBr** [comment]
@awasum yes, sending to us, the opensuse-project mailinglist or just posting in this issue is fine! Thanks!

**Comment by awasum** [comment]
I think also adding a way for people to pay for tickets using mobile money is very good for this project. What do you think?

**Comment by ChrisBr** [comment]
Please elaborate what do you mean with mobile money!

**Comment by awasum** [comment]
Telecom operators in most countries provide payment APIs for integration into e-commerce and m-commerce systems. We could design a way for integrators and conferences to add their payment details and API keys so they can be paid directly.

**Comment by ChrisBr** [comment]
@awasum nice idea, however, for this GSoC project I would really like to focus on implementing the ticket feature / payment in a proper and sane way for one provider. If this is done we can think about the next steps ;)

**Comment by awasum** [comment]
Thats works fine.

**Comment by hennevogel** [comment]
Congratulations @rishabhs95 this is your project for GSoC this year! :bouquet:

**Comment by rishabhs95** [comment]
Thanks @hennevogel and mentors for the help and guidance! 
Looking towards an exciting summer ahead! :)
