### ISSUE TITLE
Enhance visitor experience of OSEM

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#25]
**Description:** The [Open Source Event Manager](http://osem.io) is an event management app tailored to Free Software Conferences, it is developed in the [Ruby on Rails](http://rubyonrails.org/) web framework. We have several ideas to enhance the visitor experience. First of all, the event schedule isn't mobile friendly and and there is no way to have several schedule proposals to compare before releasing it (see openSUSE/osem#18 & openSUSE/osem#587). Furthermore we would like to gather feedback from the conference visitors (see openSUSE/osem#549) and improve our conference splash page (openSUSE/osem#400).

**Deliverable:** Reworked and mobile friendly schedule and splash page. Some way to gather user feedback

**Mentors:** @chrisbr @hennevogel @differentreality 

**Skills:** Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Medium

 **Getting started:** Pick one of the [Junior](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) labeled issues and get in touch with the mentors.

**Github:** https://github.com/openSUSE/osem

**Comment by abhinavsv3** [comment]
Hi
  I am interested in this project.

**Comment by ChrisBr** [comment]
Hi @abhinavsv3,

nice to see that you're interested in this project.

1) You should first start forking and checking out OSEM. Note that we have [vagrant](https://github.com/openSUSE/osem/blob/master/INSTALL.md) to make this easier for you!
2) Try to run the testsuite locally and play around with OSEM
3) Pick some [JuniorJob](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) and try to fix it.

**Comment by abhinavsv3** [comment]
sure. running it

**Comment by chocoelho** [comment]
@ChrisBr I'm also interested in it, should I get in touch with mentors after a PR gets accepted?

**Comment by hennevogel** [comment]
@chocoelho you can contact me anytime :-) You can also come and join all of the OSEM community on IRC: [irc.opensuse.org#osem](irc://irc.opensuse.org/osem). Looking forward to hear from you!

**Comment by chocoelho** [comment]
I'll do it :+1:

**Comment by awasum** [comment]
Hello @hennevogel @ChrisBr and @differentreality 
Am interested in this project. I have set up my development environment. Already attempted to fix some bugs, issue #814. Will continue working on other issues.

**Comment by 4bic** [comment]
Hey @hennevogel @ChrisBr & @differentreality 
Am interested in the project, anyone in IRC ?

**Comment by hennevogel** [comment]
Congratualiations @Ana06! This is your project for Google Summer of Code 2016 :-)
