### ISSUE TITLE
Collect material for mentors

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#3]
Collect howtos, tips, tricks, books, talks etc. about mentoring.

**Comment by hennevogel** [comment]
There is the somewhat outdated [GSoC Mentor Manual](http://en.flossmanuals.net/GSoCMentoring/)

**Comment by hennevogel** [comment]
[Mentoring toolkit](http://www.mentoring.org/downloads/mentoring_413.pdf) by mentoring.org

**Comment by cornelius** [comment]
[Mentoring HOWTO](https://people.gnome.org/~federico/docs/summer-of-code-mentoring-howto/) By Federico Mena-Quintero

**Comment by cornelius** [comment]
[KDE's mentoring information](https://community.kde.org/Mentoring)

**Comment by ChrisBr** [comment]
Added to http://opensuse.github.io/mentoring/mentor/
Can we close it? 

@hennevogel @cornelius

**Comment by hennevogel** [comment]
No I think /mentor/ we should explain what we (openSUSE) think mentoring means. what's the best way to go about it. we should tell people about best practices, what we think works and what does not, FAQ's etc. _AND_ link to the pages from others.

**Comment by hennevogel** [comment]
Done in 8988ca1401a7de8a85700dd85e41ee1dfecb7418
