### ISSUE TITLE
Inspection of installed gems with Machinery

### ISSUE THREAD

**Issue by cornelius** [openSUSE/mentoring#32]
**Description:** With [Machinery](http://machinery-project.org) you can inspect Linux systems and store the collected data as a description of the system. The description can be nicely displayed and managed by Machinery. This is useful to get insight into unknown systems, debug problems, track changes, create inventories, migrate systems, and more.

Currently Machinery collects data about RPMs and additionally about files which are not managed by RPM. These unmanaged files are collected as a plain list without looking into further structure.

This project is about  doing  deeper inspection there and for example track files which are installed directly with Ruby's `gem` command while bypassing RPM, identify to which gems they belong, and extract the list of installed gems in addition to the installed RPMs.

The same approach could be extended to other package managers such as npm, pip, etc.

  **Deliverable:** A plugin for Machinery which retrieves information about installed gems from a system and stores it in the Machinery data store. Bonus points for covering additional package managers.

  **Mentor:** @cornelius, @aduffeck 

  **Skills:** Ruby, RSpec, TDD

  **Skill Level:** Medium

  **Get started:** Get familiar with the tool, use it, have a look at the [code](https://github.com/SUSE/machinery)

**Comment by vladshablinsky** [comment]
Hi @cornelius, I'm Vlad, I have some Ruby skills and I'm interested in this project. I've installed Machinery, read the documentation, successfully tested it, inspected localhost and my Raspberry Pi with it, however It's probably not supposed to be used like that, but anyway.
As far as I understood the project is to implement something like `plugins/repositories`, but with `gem`, `pip`, etc. and provide some `Inspector` pretty similar to `RepositoriesInspector` and get gems, python packages running `gem` or `pip` or whatever with defined options. Please, correct me if I'm wrong.

I don't understand the whole codebase for now, just finished with documentation yesterday. Now on this new-comers frinedly issue https://github.com/SUSE/machinery/issues/1896.

How do I to get involved and what do I start with? Thanks!

**Comment by ChrisBr** [comment]
@vladshablinsky note that the deadline for submitting a proposal is this Friday, 25 March 19:00 UTC!

**Comment by ChrisBr** [comment]
@cornelius @aduffeck is this one still valid? If yes please open a new issue! Thanks!
