### ISSUE TITLE
Query engine for system descriptions in Machinery

### ISSUE THREAD

**Issue by cornelius** [openSUSE/mentoring#33]
**Description:** With [Machinery](http://machinery-project.org) you can inspect Linux systems and store the collected data as a description of the system. The description can be nicely displayed and managed by Machinery. This is useful to get insight into unknown systems, debug problems, track changes, create inventories, migrate systems, and more.

Machinery collects data in sections called "scopes". There are scopes for packages, users, files not managed by RPM, and more. When having descriptions from multiple systems or from different versions of the same system it often is useful to be able to query for information across system descriptions, e.g. "give me all descriptions where package x is installed in version y".

The goal of this project is to implement a query engine in Machinery which is able to execute such queries and return results in a usable way.

There are different possible approaches to this project. There is part about designing how queries are entered and how results are displayed, mostly from a user interaction point of view. There is a part about implementing the actual query, and there is a part about optimizing the query engine to be fast and efficient. One possible implementation would be to store the system descriptions in a data base and use the query engine the data base provides. Another possible implementation could work on the raw JSON data of the system descriptions. It's up for discussion between mentor and mentee on which part to put the focus. Input and ideas are welcome.

  **Deliverable:** An additional sub command of the Machinery command line tool, which takes a query and gives out results.

  **Mentor:** @cornelius, @aduffeck 

  **Skills:** Ruby, RSpec, TDD, maybe data bases, maybe a compile language such as a go

  **Skill Level:** Hard

  **Get started:** Get familiar with the tool, use it, have a look at the [code](https://github.com/SUSE/machinery)

**Comment by ChrisBr** [comment]
@cornelius @aduffeck is this one still valid? If yes please open a new issue! Thanks!
