### ISSUE TITLE
Scroll not working on modals

### ISSUE THREAD

**Issue by sonalkr132** [openSUSE/mentoring#37]
Successful projects use modal for pop up divs. They have scrollbars, however they don't work (not the scrollbar itself but the scroll event). Scroll starts working after I have triggered some other event (like right click, open inspector window etc).
Can some please confirm that I am not the only one having this issue?

**Comment by ChrisBr** [comment]
Works for me! 
Which browser? Have you tried a different browser?

**Comment by sonalkr132** [comment]
It doesn't work on Chrome Version 46.0.2490.80 (64-bit)
I just tired it on Mozilla Firefox 41.0.2 and it worked there. It can be closed?

**Comment by sonalkr132** [comment]
I am guessing osem.io uses same technique for osem features (on homepage). However scroll on pop-up modal works there.

**Comment by ChrisBr** [comment]
Not reproducible ...
