### ISSUE TITLE
Improve Portus LDAP support

### ISSUE THREAD

**Issue by mssola** [openSUSE/mentoring#39]
**Project Title:** Improve LDAP support

**Description:** this project is based on two main points, and an optional one:
1. Add LDAP Group support: This is better explained [here](https://github.com/SUSE/Portus/issues/734).
2. Improve the current integration testing setup to include all the possible
   LDAP configurations.
3. (Optional) General improvements on LDAP handling that the student might feel
   that are needed. There should be total freedom for the student to propose
   ideas that might be interesting _and_ deliverable for the GSoC period.

**Deliverable:** LDAP Group support should be merged into the `master` branch.
Improvements on our integration infrastructure are also desirable.

**Mentor:** Miquel Sabaté Solà @mssola / msabate@suse.com
**Co-Mentor** Flavio Castelli @flavio / fcastelli@suse.com

**Skills:** Ruby, Ruby on Rails, Docker.

**Skill Level:** Medium

**Get started:** Take a look at our [issues](https://github.com/SUSE/Portus/issues) on Github. Try to fix some (note that there are some [junior jobs](https://github.com/SUSE/Portus/labels/junior%20job)).

**Comment by mssola** [comment]
There are some open issues in Portus about this. Students willing to take this project should:

1. Get familiar with Portus. Install it in [any of the recommended setups](https://github.com/SUSE/Portus/wiki#developmentplayground-environments), play with it.
2. Take a look at [junior jobs](https://github.com/SUSE/Portus/labels/junior%20job), try to fix one.
3. Propose some possible improvement, even if there's no current issue open for that.

**Comment by ChrisBr** [comment]
@mssola is this one still valid? If yes please open a new issue! Thanks!

**Comment by mssola** [comment]
Not valid anymore, so I'll keep it closed. Thanks for taking care of this 👍
