### ISSUE TITLE
Collect projects that have mentors

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#4]
What FOSS projects do we run that have the people/structure to do mentoring?

**Comment by hennevogel** [comment]
[Machinery](http://machinery-project.org/)

**Comment by hennevogel** [comment]
[Yast](http://yast.github.io/)

**Comment by hennevogel** [comment]
[Portus](https://suse.github.io/Portus/)

**Comment by hennevogel** [comment]
[OSEM](http://osem.io)

**Comment by hennevogel** [comment]
[openQA](http://os-autoinst.github.io/openQA/)

**Comment by hennevogel** [comment]
[OBS](http://openbuildservice.org/)

**Comment by hennevogel** [comment]
[Snapper](http://snapper.io/)

**Comment by ChrisBr** [comment]
Machinery, YaST, Portus, Jangouts & OSEM already added to the page! The other ones we can add as soon as the have a mentoring projects (adding a project without mentoring project doesn't make sense I think).

How to add a new project is described in the [README.md](https://github.com/openSUSE/mentoring#adding-new-project)

@hennevogel can we close it?

**Comment by ddemaio** [comment]
@ChrisBr when do you think we will go live? I can write something up and put out on social media.

**Comment by ChrisBr** [comment]
@ddemaio I'd at least wait till we have a nice domain for the page, see https://github.com/openSUSE/mentoring/issues/1.

But I'd like that we write a blog article about the booth tomorrow at the university! I try to make some pictures and write sth down, maybe you can work out a blog article!

**Comment by hennevogel** [comment]
Yes everything is there!
