### ISSUE TITLE
MirrorPinky - self management interface for mirror administrators

### ISSUE THREAD

**Issue by lrupp** [openSUSE/mentoring#42]
**Project Title**: MirrorPinky - A web frontend for mirror administrators

**Description**: You might know [MirrorBrain](http://mirrorbrain.org) already: our download redirector and Torrent/Metalink generator used u.a. on [download.opensuse.org](http://download.opensuse.org/). It's really a great tool that plays a hidden key role inside the openSUSE infrastructure and is meanwhile used by many others ( KDE, VLC, DocumentFoundation, ArchLinux - just to name a few).

But while the amount of openSUSE mirrors is increasing over the time (currently we have >180 mirrors in our database!), the amount of main administrators for the database itself is not increasing as well.

It happens, that mirrors want to limit the traffic for a specific time (means for us: decreasing the score of this specific mirror) or changing their setup (means for us: adapting the URLs for FTP, HTTP, rsync or the operator Name and Url - or even the Name and Email of the mirror admin). Not thinking about the work for adding new mirrors or removing old ones. Sometimes it might also be enough to disable a mirror for a short time - and re-enable it after the maintenance work is done. All this is currently done manually on request via mail to admin@opensuse.org or mirror@opensuse.org

But as most of the stuff above only affects single mirrors that are already maintained by people who should know what they are doing, why not allowing them to do the requested steps on their own?

Maybe they can even trigger a "rescan" of their mirror once it is added - or something has changed/fixed?

**Deliverable**: 
- Enhance the current code status on https://github.com/openSUSE/mirrorpinky - finish the outstanding bits and pieces to get the code production ready
- provide tests that cover nearly all current features
- help with packaging and releasing the stuff to the outside world

**Mentor**:
- Lars Vogdt Lars.Vogdt@suse.com / @lrupp 
- Marcus Rueckert Marcus.Rueckert@suse.com / @darix 

**Skills**:
- Ruby (required)
- Rails (required)
- CSS/HTML5 (strongly recommended)
- MirrorBrain (strongly recommended)
- PostgreSQL (recommended)
- Python/Perl/RPM packaging (recommended)

**Skill Level**: medium 

**Get started**: 
General everything should be collected/done using https://github.com/openSUSE/mirrorpinky 
- setup your local instance of MirrorPinky  (see [README.development.md](https://github.com/openSUSE/mirrorpinky/blob/master/README.development.md))
- start working on the things listed in the TODO section on the Github repo (or add more ;-)

**Comment by ChrisBr** [comment]
@lrupp @darix is this one still valid? If yes please open a new issue! Thanks!
