### ISSUE TITLE
Improve the UI of Portus

### ISSUE THREAD

**Issue by mssola** [openSUSE/mentoring#44]
**Project Title:** Improve the UI of Portus

**Description:** In this project we encourage students to try to improve the UI of Portus. Some known issues from Portus' UI are:

- Don't allow users access to the hidden team.
- Assets should be served differently. For example, it doesn't make much sense to serve the font "Pacifico" for every page, when it's only used in error pages.
- Create a help section: a simple link to our documentation could be a start, but we would like to hear more ideas.
- Improve the search feature so it also searches for teams and namespaces.
- The repositories container in the dashboard page is a bit cumbersome when there are lots of repos:
    - Allow a search filter.
    - Only show a fixed amount of rows, where the last row is "Show x more repositories", where x is the amount of repositories that are not being shown.
    - Sort by last pushed or last updated
- Allow the filtering of namespaces, teams and team members in the different pages of Portus.
-  There should be an "Explore" feature where even non-logged in users could get a list of interesting public namespaces/repositories.

Besides the known issues, we greatly encourage students to try to come up with other improvements in this regard.

**Deliverable:** most of the tasks mentioned before should be merged into the `master` branch.

**Mentor:** Miquel Sabaté Solà @mssola / msabate@suse.com

**Co-Mentor:** Flavio Castelli @flavio / fcastelli@suse.com

**Skills:** CoffeeScript, CSS, Ruby on Rails

**Skill Level:** Medium

**Get started:**  Take a look at our [issues](https://github.com/SUSE/Portus/issues) on Github. Try to fix some (note that there are some [junior jobs](https://github.com/SUSE/Portus/labels/junior%20job), [UI issues](https://github.com/SUSE/Portus/labels/ui), [UX issues](https://github.com/SUSE/Portus/labels/ux)).

**Comment by abhinavsv3** [comment]
Hi I am interested in working on this project.

**Comment by mssola** [comment]
Hi @abhinavsv3, we don't know how many open slots does openSUSE have for GSoC yet. AFAIK, we'll get this information as of 29th of February. Whenever we know, we'll get back to you :wink:

**Comment by abhinavsv3** [comment]
Yeah sure.
I awaiting you mail.

Abhinav

**Comment by ChrisBr** [comment]
@abhinavsv3 @mssola openSUSE has been accepted for this year, so feel free to start ;)

**Comment by arun1595** [comment]
I would like to contribute to this project. Need more information to get started.

**Comment by abhinavsv3** [comment]
Hi
  That's a great news to me. Now can you help me to start? where do I start
. Is there some really intersting proposal that I can draw my contribution
to.

Abhinav

On Wed, Mar 2, 2016 at 5:37 PM, Arun Kumar <notifications@github.com> wrote:

> I would like to contribute to this project. Need more information to get
> started.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openSUSE/mentoring/issues/44#issuecomment-191317659>.
>



-- 

Abhinav S V ,
IV Year , B.Tech
Computer Science and Engineering
SASTRA UNIVERSITY , Thanjavur
TAMILNADU

**Comment by msfernandes** [comment]
Hi! I am interested to work with this project too!
@mssola can you indicate an issue to begin?

**Comment by abhinavsv3** [comment]
@mssola @ChrisBr  Can you also suggest me bug/issues to start with?

**Comment by mssola** [comment]
Glad to see so many people willing to take part on this project :D 

First of all, what I would recommend is to get acquainted with Portus. Install it in [any of the recommended setups](https://github.com/SUSE/Portus/wiki#developmentplayground-environments), play with it.

Specifically for this project, you'll see current [ui](https://github.com/SUSE/Portus/labels/ui) and [ux](https://github.com/SUSE/Portus/labels/ux) issues. Some of them are even junior jobs. Take your time and try to fix either of those. Also, it would be appreciated if you could come up with an improvement regarding UI/UX, even if simple.

**Comment by ChrisBr** [comment]
Also, as I see that there are already three students interested in this project, please also consider some other project where we don't hat have students yet!

**Comment by msfernandes** [comment]
There is a specific irc channel for portus project?

**Comment by mssola** [comment]
@msfernandes not yet. We are working on that actually. I'll come back to you whenever I have any news on that :wink:

**Comment by msfernandes** [comment]
@mssola where we can talk about gsoc?

**Comment by mssola** [comment]
@msfernandes for now feel free to use containers@lists.suse.com. The team working on Portus is subscribed to this list, so it should be fine :wink:

**Comment by AdityanJothi** [comment]
Hi im interested in working on this project , are there any free slots ?

**Comment by hennevogel** [comment]
Congratulations @msfernandes this is your project for GSoC this year! :bouquet:
