### ISSUE TITLE
Improve Machinery's Code Base through Refactoring

### ISSUE THREAD

**Issue by mauromorales** [openSUSE/mentoring#46]
**Description:** The [Machinery project](http://machinery-project.org/) has been evolving in a good pace for the last couple of years by adding features and fixing bugs in an agile way. However there are places where our code base could benefit from:
- a better design
- more readability
- better performance

We will achieve these goals through refactoring so we don't alter the external behavior of the code in the process of getting the benefits in our internal structure.

**Deliverable:** At the end of this project the student will be able to:
- identify some code smells
- apply a well known refactoring method
- ensure that no regressions were introduced

**Mentor:** @mauromorales

**Skills:** Ruby, RSpec, TDD, git

**Skill Level:** Medium - Hard

**Get started:** The best way to get started is to:
- Get familiar with Machinery, use it, have a look at the [code](https://github.com/SUSE/machinery) and some [examples](https://github.com/openSUSE/machinery-examples).
- Tackle one of our [newcomer friendly issues](https://github.com/SUSE/machinery/issues?q=is%3Aissue+is%3Aopen+label%3A%22Newcomer+friendly%22)
- Read the refactoring book by Martin Fowler (there is a [Ruby edition](https://read.amazon.com/kp/embed?asin=B002TIOYWG&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_qQgXwb031RZEX))

**Comment by ajaivgeorge** [comment]
I am interested in this project. I am acquainted with Ruby, RSpec and Cucumber and have read Martin Fowler's Refactoring book. Can you please guide me in getting familiar with the codebase.

**Comment by mauromorales** [comment]
@ajaivgeorge glad to hear you are interested :) and sure I'll be happy to shed some light.

Have you already installed and used machinery? this will be the best way to get started so you get acquainted with our terminology (i.e. scopes, inspection, description). Also keep an eye to our [documentation](http://machinery-project.org/docs/).

Once you have some mileage with machinery make sure you can run the tests locally and understand our development toolchain.

The last step would be to dive into those tests, they will be your guide on how the machinery code is structured and our safety net to do the refactoring.

Cheers!

**Comment by ajaivgeorge** [comment]
Thank you. I have cloned the repo, and installed it. I will have a look at the tests and the docs and get back to you.

**Comment by mauromorales** [comment]
@ajaivgeorge I've added a repo with some use case examples make sure you also have a look at them [here](https://github.com/openSUSE/machinery-examples)

**Comment by mauromorales** [comment]
I've also added a link to the issue with some [newcomer friendly issues](https://github.com/SUSE/machinery/issues?q=is%3Aissue+is%3Aopen+label%3A%22Newcomer+friendly%22)

**Comment by ChrisBr** [comment]
@ajaivgeorge note that the deadline for submitting a proposal is this Friday, 25 March 19:00 UTC!

**Comment by ChrisBr** [comment]
@mauromorales is this one still valid? If yes please open a new issue! Thanks!
