### ISSUE TITLE
Get a static (gh-pages) web site going

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#5]
## Goals

* Collect mentoring projects and present them to students/sponsors
* Provide mentoring for mentors (materials, hints, tips & tricks. see #3)
* Present an overview of our Free Software development projects

**Comment by ChrisBr** [comment]
I can take this! @hennevogel maybe we can talk today briefly about a nice template / layout...

**Comment by hennevogel** [comment]
First version is in `gh-pages` now. I'll see what I can do about the domain.

**Comment by hennevogel** [comment]
http://101.opensuse.org is there too. Fixed! :-)
