### ISSUE TITLE
Umbrella for coala

### ISSUE THREAD

**Issue by sils1297** [openSUSE/mentoring#51]
Hi,

we are coala (coala-analyzer.org) and have not been accepted for GSoC so far. We have lots of students who already contribute to our project and really want to do a GSoC with us. We have mentorship capabilities for several projects as well and mentored two students successfully last year.

If you have need for it I'd be happy to help out administering your GSoC with my experience from GNOME. We'd love to participate under your umbrella in this GSoC.

I didn't find any IRC channel or email, if you wish to continue this as a private discussion, please write me an email to lasse.schuirmann@gmail.com .

**Comment by ChrisBr** [comment]
Hi @sils1297,

Google accepted openSUSE as mentoring organization this year. However, we didn't apply as an umbrella organization, so I assume it's not possible to include projects from a different organization after the application period.

However, I'll check and discuss this with our organization team.

**Comment by sils1297** [comment]
hey please don't do any effort, I have just come to an agreement with the PSF.

**Comment by sils1297** [comment]
FWIW google likes umbrellas a lot and I thought the whole goal of this repo is that you're an umbrella also for possible outside projects so formally it shouldn't make any difference.
