### ISSUE TITLE
Get all accepted mentors to subscribe to gsoc-mentors@opensuse.org

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#54]

**Comment by ChrisBr** [comment]
Sent an email to all mentors, we have to check next week if we got everyone ...

**Comment by jreidinger** [comment]
I do not see mailing list at https://lists.opensuse.org/ so I cannot subscribe via UI. BTW I used to be in old one and was removed.

**Comment by ChrisBr** [comment]
@jreidinger the list is private and moderated, so not listed on https://lists.opensuse.org/. We removed everyone last week! Just sending an email to ``gsoc-mentors+subscribe@opensuse.org`` should work. Thanks!

**Comment by jreidinger** [comment]
ok, thanks.
