### ISSUE TITLE
Distribute Materials to attract students

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#56]
We need to collect materials we can hand out to people so they can distribute them to their local universities. @ChrisBr you had a PDF somewhere right?

Distribute those to:
- [ ] openSUSE 
- [ ] SUSE

**Comment by ChrisBr** [comment]
Yep, let me know if you want me to adapt them.
- [opensuse101.pdf](https://github.com/openSUSE/mentoring/files/159897/opensuse101.pdf)
- [gsoc.pdf](https://github.com/openSUSE/mentoring/files/159898/gsoc.pdf)

(the second one is the official GSoC press release)

**Comment by ChrisBr** [comment]
@hennevogel where do we want to store the material?
