### ISSUE TITLE
Blog about the projects

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#57]
We should present the individual projects, what they are about and how students can start (basically a text out of the issue) on news.opensuse.org

**Comment by cornelius** [comment]
I blogged about the projects I proposed on my personal blog: http://blog.cornelius-schumacher.de/2016/03/students-join-summer-of-code.html

**Comment by ChrisBr** [comment]
@cornelius cool! Do we want to redistribute the article to news.o.o?

**Comment by cornelius** [comment]
@ChrisBr I don't think the article would fit news.o.o as it is. Better write another one, which covers it from an openSUSE project perspective.
