### ISSUE TITLE
Setup SUSE Lunch&Learn

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#59]
This will be next Thursday. We need to get a short presentation together about GSoC and what people can do for it.

**Comment by ChrisBr** [comment]
Ok, let's do this on monday!

**Comment by hennevogel** [comment]
Agenda:

* Introduce the general ideas of 101
  * Build a community of mentors in openSUSE
  * Help people to learn mentoring
* Introduce GSoC
  * The general idea
  * Why is this important?
  * openSUSE GSoC History
    * People that came out of this?
    * Software that came out of this?
  * The timeline
* Which of our FOSS Projects participate in GSoC
* Help with mentoring
  * What do I have to do when I'm a mentor?
  * Show the mentoring projects that need a mentor
* Help to attract students
  * Do you know a student?
  * Do you know a Professor?
  * Distribute our materials
* Other mentoring programs that we want to run through 101
  * RGSoC, Outreachy, Coder Dojo
* How to help with Administration?
  * We handle everything in github issues
* Q&A

**Comment by ChrisBr** [comment]
done!

**Comment by ChrisBr** [comment]
Maybe we should collect the slides and video somewhere?

**Comment by mssola** [comment]
@ChrisBr I'd appreciate that, because I couldn't attend :(

**Comment by hennevogel** [comment]
Absolutely. If the video is good enough we might even add it to the page. The slides are just copy&paste from the 101 page anyway :-)

**Comment by ChrisBr** [comment]
@hennevogel also we could submit it as a OSC16 talk ...
