### ISSUE TITLE
Improve one-click installer

### ISSUE THREAD

**Issue by ChrisBr** [openSUSE/mentoring#63]
**Project Title:** Improve one-click installer

**Description:** The one-click installer would benefit greatly from improved features. Some of these are: 

- Port the application to use Qt5 instead of Qt4.
- Localization.
- Handling conflicts and dependency in the backend.
- Better progress interface so the user can see if the application is downloading or installing the package.
- Show which repository each package is coming from.
- etc.

Some mockups of how the application might look can be seen [here](https://github.com/openSUSE/one-click-installer/wiki).

**Deliverable:** A version of the one-click installer with much improved user interface which is easier to use, gives more information and looks nicer than the current version.

**Mentor:** @antlarr / alarrosa@suse.com

**Skills:** Some knowledge of C++ needed. It would be nice if the student knows the Qt libraries, but it should be possible to learn them while working on the project. Some XML knowledge would be nice too, as the project involves some XML parsing (which is already implemented but might need some changes).

**Skill Level:** Medium

**Get started:** To learn about Qt:

- [Qt Examples and Tutorials](http://doc.qt.io/qt-5/qtexamplesandtutorials.html)
- [Qt Documentation](http://doc.qt.io/qt-5/reference-overview.html)

To port one-click installer to Qt5:

- [Qt4.x to Qt5 Porting guide](https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5)

Start working on one-click installer:

- [one-click installer repository](https://github.com/openSUSE/one-click-installer)

**Comment by ChrisBr** [comment]
![one-click-2](https://cloud.githubusercontent.com/assets/3799140/13884200/99e6a298-ecf2-11e5-87fa-4e9efcb22ffa.png)

**Comment by shalomRachapudi** [comment]
Good day! Hope you are doing fine. I'm interested in this project. I'm proficient in C++ and know a thing or two about Qt libraries (willing to learn on-the-fly). I'd love to upload my proposal but couldn't find a template on the site. I found the project details on GSoC webpage. Looking forward to your reply.
- Shalom

**Comment by ChrisBr** [comment]
@shalomRachapudi please use this [template](https://github.com/openSUSE/mentoring/blob/gh-pages/templates/gsoc.md)

**Comment by ChrisBr** [comment]
@shalomRachapudi note that the deadline for submitting a proposal is this Friday, 25 March 19:00 UTC!

**Comment by shalomRachapudi** [comment]
Sure, I'm on it. :) @ChrisBr

**Comment by hennevogel** [comment]
Congratulations @shalomRachapudi this is your project for GSoC this year! :bouquet:
