### ISSUE TITLE
Conference Info Screen for OSEM

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/mentoring#65]
**Project Title:** Conference Info Screen for the [Open Source Event Manager (OSEM)](http://osem.io/)

**Description:** From the data available in OSEM build a page that conference organizers can show on screens throughout the venue containing information like the the next talks title&speaker, tweets about the conference, sponsors etc.

**Deliverable:** A new page in the OSEM ruby on rails app.

Mentors: @chrisbr @hennevogel @differentreality

Skills: Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Easy

 **Getting started:** Pick one of the [Junior](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior) labeled issues and get in touch with the mentors.

**Github:** https://github.com/openSUSE/osem

**Comment by Ana06** [comment]
@hennevogel @ChrisBr @differentreality what the state of this? I remember there were some work on it. Can we close it or should we keep it open? 🤔

**Comment by differentreality** [comment]
**not** implemented :/
https://github.com/openSUSE/osem/pull/1119

**Comment by ChrisBr** [comment]
I would close it for now as we said we don't want to do a project in OSEM this year!
