### ISSUE TITLE
Implement the server command in zypper-docker

### ISSUE THREAD

**Issue by mssola** [openSUSE/mentoring#68]
**Project Title:** Implement the server command in zypper-docker
 
**Description:** The aim of this project is to allow zypper-docker to act as a web application. With this command, zypper-docker will provide an API in which clients will be able to check whether an image contains security vulnerabilities. Therefore, the student should do the following:
 
1. Propose an API.
2. Implement the endpoints of the API
3. Properly implement the backend code needed to fulfill the API.
 
Everything should be properly tested with both unit and integration tests.
 
**Deliverable:** zypper-docker should be able to act as a web application. Clients will be able to perform requests asking for the security status of an image and get back a proper response.
 
**Mentor:** Miquel Sabaté Solà @mssola / msabate@suse.com
**Co-Mentor:** Thomas Hipp @monstermunchkin / thipp@suse.com
 
**Skills:** Go, docker. Experience in designing APIs is a plus.
 
**Skill Level:** Hard
 
**Get started:** You should be acquainted with the code before going for this project. For this, we recommend tackling issues with the label [junior job](https://github.com/SUSE/zypper-docker/labels/junior%20job). After that, we will ask students to give a general overview on how they are going to accomplish this feature (nothing too deep, just a general overview).

**Comment by chawlanikhil24** [comment]
I'd like to work on the issue.

**Comment by ChrisBr** [comment]
@mssola ping!

**Comment by mssola** [comment]
@chawlanikhil24 sorry for not getting to you sooner! As the description says, you should try to tackle on the issues marked as [junior jobs](https://github.com/SUSE/zypper-docker/labels/junior%20job).

**Comment by chawlanikhil24** [comment]
@mssola  Its alright and thank you for the information.

**Comment by Ana06** [comment]
@mssola  what is the state of this? Is it done? can we close the issue?
