### ISSUE TITLE
Improve the UI of Portus

### ISSUE THREAD

**Issue by mssola** [openSUSE/mentoring#71]
**Project Title:** Improve the UI of Portus

**Description:** the UI and the UX of Portus passed GSoC 2016 thanks to @msfernandes, but there is still some pending issues to be fixed, plus some new issues:

- Allow anonymous users to see the publicly available images (see [#1129](https://github.com/SUSE/Portus/issues/1129)).
- Extend the version info as shown on the web page (see [#1023](https://github.com/SUSE/Portus/issues/1023)).
- Perform more checks on the client side (e.g. [#861](https://github.com/SUSE/Portus/issues/861)).
- The help section should be its own page, so it's available offline.

Besides this, students should also provide ideas of their own.

**Deliverable:** the issues mentioned above should be implemented by the end of the GSoC period. Moreover, we expect students to also have implemented improvements that they have proposed.

**Mentor:** Miquel Sabaté Solà @mssola / msabate@suse.com
**Co-Mentor:** Rafael Fernández López @ereslibre / rfernandezlopez@suse.com

**Skills:** CoffeeScript, CSS, Ruby on Rails

**Skill Level:** Medium

**Get started:** Take a look at our [issues](https://github.com/SUSE/Portus/issues) on Github. Try to fix some (note that there are some [junior jobs](https://github.com/SUSE/Portus/labels/junior%20job), [UI issues](https://github.com/SUSE/Portus/labels/ui), [UX issues](https://github.com/SUSE/Portus/labels/ux)).

**Comment by nishanMaduwantha** [comment]
I'm third year student of  Faculty of Information Technology of University of Moratuwa. I have worked  coffeeScript and CSS in my second year project. So I'm interested in your project. So would you please tell me proceed  further

**Comment by mssola** [comment]
@nishanMaduwantha as written in the description, take a look at our [issues](https://github.com/SUSE/Portus/issues) on Github. Try to fix some (note that there are some [junior jobs](https://github.com/SUSE/Portus/labels/junior%20job), [UI issues](https://github.com/SUSE/Portus/labels/ui), [UX issues](https://github.com/SUSE/Portus/labels/ux)).
