### ISSUE TITLE
Hosted version of OSEM

### ISSUE THREAD

**Issue by lagartoflojo** [openSUSE/mentoring#72]
### Hosted version of OSEM

**Description:** The Open Source Event Manager (OSEM) is an event management app tailored to Free Software Conferences, developed in Ruby on Rails. Right now, it is a self-hosted solution, meaning that every conference that wants to use OSEM must have their own servers to host OSEM, as well as install the application and its dependencies. This has some drawbacks: it requires a high technical knowledge (specifically with Rails), and it makes the conference responsible for the up-time and security of the servers. Conference organizer are already quite busy with organizing the conference, and managing servers is not something they want to spend their energy on.
In this project, we want to create a hosted version of OSEM. This means that once installed on a server, any conference organizer in the world will be able to use that installation to create and manage their conference. Sign up, enter your conference details, and off you go.

Some of the work and features involved in this project can include:

- Creating a new level in the permissions hierarchy, "site admins". They would be able to configure site-wide settings. Current conference admins should only be able to manage their own conferences, and not others'.
- Moving some settings that are currently application-wide into conferences (for example, Stripe payment tokens).
- Incorporating revenue-generating features for the hosted OSEM site administrator, for example by earning a percentage of each ticket sold.
- Creating a nice landing page that explains what users can do there, as well as showing upcoming conferences.
- Adding the ability for conferences to use their own domain, while in reality they load from the hosted OSEM's servers.

**Deliverable:** All the necessary changes in the OSEM code to be able to achieve the project proposal. A demo hosted version of OSEM should be running on a publicly accessible server (eg. Heroku).

**Mentor:** Hernán Schmidt
 - GitHub: @lagartoflojo
 - IRC: hernansp on freenode#osem
 - Email: hernan [dot] schmidt [at] gmail [dot] com

**Skills:** Ruby on Rails.

**Skill Level:** Medium

**Getting started:** Start with submitting a PR of a [junior job](https://github.com/openSUSE/osem/issues?q=is%3Aopen+is%3Aissue+label%3AJunior). Once you've done that, submit your project proposal as early as possible so that we can polish it before the submission deadline.

**IMPORTANT: Students will only be considered if they have successfully worked on at least one junior job, as well as interacted with the OSEM community through GitHub and/or IRC (`#osem` channel on freenode).**

**Comment by shlok007** [comment]
Hi! I am a second year student pursuing undergraduate degree in Computer Science. I would really like to work on this. :slightly_smiling_face:

**Comment by Shriyanshagro** [comment]
Hello @lagartoflojo  I'm a GSoC aspirant and find this idea very interesting and want to discuss more about it?? Can I get you IRC nick?? or ping me at my IRC nick: "Shriyanshagro"

**Comment by Ana06** [comment]
@lagartoflojo we can close this, right?

**Comment by lagartoflojo** [comment]
Yup!
