### ISSUE TITLE
Join Forces

### ISSUE THREAD

**Issue by sils** [openSUSE/mentoring#75]
Hey, we have built projects.coala.io which is serving a similar purpose, I was wondering if that might help you. Joining two projects to one in some way usually means better quality and less maintenance for all parties ;)

**Comment by ChrisBr** [comment]
Hi @sils,
I saw your mail on GSoC mentors, totally forget to reply, sorry :/ Sure, why not!

**Comment by sils** [comment]
CCing @sims1253 who's our dedicated GSoC admin this year and @hemangsk who's the developer of projects.coala.io. I think the easiest way I can imagine a collaboration is you using projects.coala.io for organizing your projects and helping us making it customizable for other orgs.

We wanted a yml file and it should be easier to make a custom theme.

Is this interesting for you? I'm sure @hemangsk will be super happy to help us doing that.

**Comment by ChrisBr** [comment]
@sils at least not for this year as GSoC deadline is in two days. Maybe for future versions, however, we just started developing this tool last edition and put a lot of thought into it. Means we don't really want to change the workflow again (basically using github as a backend and jekyll as frontend).

**Comment by sils** [comment]
well our page does the same, github and a static HTML page with no ties
attached.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by ChrisBr** [comment]
@sils will look into it, thanks
