### ISSUE TITLE
Add sessions recording support to Jangouts

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/mentoring#76]
**Description:** Jangouts is a videoconferencing solution that can be used to hold meetings with any number of participants. But currently there is no way to record those meetings in order to watch them again. That's a feature that will make Jangouts suitable for many more use cases, like online workshops. This [Issue](https://github.com/jangouts/jangouts/issues/34) at GitHub describes some possible approaches to implement such feature.

**Deliverable:** A mechanism to record and play Jangouts sessions, either integrated in Jangouts itself either as an external tool that can connect to a session and produce a video out of it.

**Mentors:** @ancorgs / ancor@suse.com and @imobach / igonzalezsosa@suse.de

**Skills:** JavaScript

**Skill Level:** medium

**Getting started:** Pick something from the list of [junior jobs](https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22) of Jangouts and try to do something about it.

**Github:** https://github.com/jangouts/jangouts/

**Comment by Qantas94Heavy** [comment]
Hi, I'm interested in taking on this project for GSOC. Just to clarify, this need to record the video and audio of all participants, as well as any text conversations that take place -- is that right?

**Comment by ChrisBr** [comment]
@ancorgs ping!

**Comment by imobachgs** [comment]
@Qantas94Heavy Audio/Video should be enough. Having the conversation included is a plus IMHO.

**Comment by ancorgs** [comment]
@Qantas94Heavy I agree with @imobachgs. Take a look to the [Janus Google group](https://groups.google.com/forum/#!forum/meetecho-janus) and you will see we are not alone. Some people share there experiments and thoughts about recording Janus conversations.
