### ISSUE TITLE
Add full integration (end-to-end) tests to Jangouts

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/mentoring#77]
**Description:** With every new release of Jangouts or every time we want to update the version of Janus Gateway deployed in our servers, we need to ensure everything still works with several browsers (and several versions) in various operating systems. That's something that should be automated (in the same way that we already have some Jasmine-based unit test for the internal Jangouts components). This project is about researching about the possibilities and designing some solution that allows to automatically verify if Jangouts works by firing some web browsers, connecting them to a Jangouts instance and checking that the browsers can communicate through it.

**Deliverable:** A piece of software that can run or emulate several browsers with their own virtual cameras/microphones joining to a Jangouts room. Desirably with different versions of each browser. The tool should report whether a given Jangouts instance is working as expected.

**Mentors:** @imobachgs  igonzalezsosa@suse.de and @ancorgs / ancor@suse.com

**Skills:** JavaScript. Testing

**Skill Level:** hard

**Getting started:** Pick something from the list of [junior jobs](https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22) of Jangouts and try to do something about it.

**Github:** https://github.com/jangouts/jangouts/

**Comment by nikhilrayaprolu** [comment]
@imobachgs @ancorgs I would like to work on this.

**Comment by imobachgs** [comment]
@nikhilrayaprolu Sorry but I overlooked your message. A good starting point would be trying to work in some of our junior jobs. Apart from that, you'll need to prepare and submit your proposal for the project. Please, let me know if you need help with that.

**Comment by nikhilrayaprolu** [comment]
Thank you for your reply. I would like to work on angular-2 branch but I couldn't find any junior jobs related to angular-2. I am happy if you could assign me an issue related to angular-2 .

**Comment by nikhilrayaprolu** [comment]
@ancorgs @imobachgs I have shared my draft , can you please review it and share your views on it.
