### ISSUE TITLE
Revamp Jangouts User Interface

### ISSUE THREAD

**Issue by imobachgs** [openSUSE/mentoring#80]
**Description:** Jangouts is a really nice videoconferencing tool but it lacks of a good User Interface. Developers have been busy adding new features but, to be honest, the interface didn't get too much love. So the objective of this project is to design and implement a new user interface to improve the UX and make Jangouts great. During the last GSoC, Jangouts was ported to Angular 2, so a mobile friendly [Material Design](https://material.angularjs.org/) based interface looks like a reasonable approach. However, we're open to other proposals.

**Deliverable:** A new brand user interface for Jangouts based on Angular 2

**Mentor:** @imobachgs  / igonzalezsosa@suse.de and @ancorgs / ancor@suse.com

**Skills:** JavaScript.

**Skill Level:** Medium

**Getting started:** Pick something from the list of [junior jobs](https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22) of Jangouts and try to do something about it. For this particular project, you should also check out the [angular-2 branch](https://github.com/jangouts/jangouts/tree/angular-2) (although we're still working in this branch to get it working at 100%).

**Github:** https://github.com/jangouts/jangouts/

**Comment by mohsini172** [comment]
I want to work on this project. where should I start?

**Comment by ancorgs** [comment]
@mohsini172 is explained in the "getting started section" - try to fix some junior job. For this particular project, it would also be important to know what you plan in order to improve the interface.

**Comment by dart-wakar** [comment]
I was unable to setup the janus webrtc via the one click install available on the opensuse software repository.Is there any other way to setup this

**Comment by ChrisBr** [comment]
@dart-wakar did you try to follow the installation guide in the readme?
https://github.com/jangouts/jangouts/#installation

**Comment by sj29-innovate** [comment]
which janus-gateway package has to be installed from the opensuse software repository ?

**Comment by ChrisBr** [comment]
@sj29-innovate depends on what distribution you use ;)

**Comment by coolsaiification** [comment]
I wish to work on this project. How can I contribute?

**Comment by ancorgs** [comment]
@coolsaiification You have information about the current state of this at https://github.com/aniabui/jangouts/releases/tag/v0.4.6-redesign

Check the work referenced there, checkout the corresponding branch, ask any question in the irc channel or the Jangouts google group... and start hacking!

**Comment by Ana06** [comment]
@ancorgs @imobachgs what is the state of this? Is it done? can we close the issue?
