### ISSUE TITLE
Integrate callstats.io into Jangouts

### ISSUE THREAD

**Issue by ancorgs** [openSUSE/mentoring#82]
**Description:** Callstats.io is a SaaS service that helps WebRTC services detect and diagnose media and network quality issues. It would be nice if companies and individuals deploying Jangouts would have the possibility to use this service in a straightforward way. This task can be completed by sending WebRTC events and measurement data from the Jangouts application and the Janus media server in real-time to callstats.io. The developer is expected to integrate the [callstats.io REST API](https://docs.callstats.io) with the WebRTC components in Jangouts and Janus. The Jangouts app will send [endpoint stats](http://w3c.github.io/webrtc-stats/) and Janus will send the stats related to the [WebRTC gateway](https://www.callstats.io/bridge-metrics/).

**Deliverable:** A new configuration option in Jangouts (maybe even needing explicit acceptance for the participant to be really enabled) to activate the optional callstats.io integration. If enabled, it will show the stats on the callstats.io dashboard from the Jangouts endpoint and the corresponding Janus server.

**Mentor:** @ancorgs / ancor@suse.com and karthik@callstats.io

**Skills:** JavaScript and C.

**Skill Level:** Medium

**Getting started:** Pick something from the list of [junior jobs](https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22) of Jangouts and try to do something about it. Also check the [callstats.io documentation](http://docs.callstats.io/).

**Github:** https://github.com/jangouts/jangouts/

**Comment by Ana06** [comment]
@ancorgs what is the state of this? Is it done? can we close the issue?
