### ISSUE TITLE
Improve user experience in OBS

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/mentoring#88]
**Project Title:** Improve user experience in [Open Build Service](https://github.com/openSUSE/open-build-service)

**Description:** 

[Open Build Service](https://github.com/openSUSE/open-build-service), normally abbreviated as OBS, is a generic system to build and distribute binary packages from sources in an automatic, consistent and reproducible way. The openSUSE public instance is running at https://build.opensuse.org.

OBS user interface is in many cases not intuitive and difficult to use, especially for new users. There are workflows that could be improved to make users lives much more comfortable and new features that could be introduced. During the last years, the large OBS community has suggested many improvements in this regard. The objective of this project is to implement some of these ideas:

- The project monitoring page gives users an overview of all the package builds of a project, for example on the [OBS:Server:Unstable page](https://build.opensuse.org/project/monitor/OBS:Server:Unstable). The content of this page has been increased to the point that it is now overloaded, looks broken and is really difficult to read. During the project a better structured page will be designed and implemented. For example, icons could be used for states instead of words, build target with similar names could be condensed to tabs and the table could be replaced with individual package divs. Related issue: https://github.com/openSUSE/open-build-service/issues/410.

- Currently it is only possible to upload one file at a time, which is painful when uploading many files. We want to allow uploading multiple files at once to make this task faster and less repetitive for our users. We also have a really cool feature to upload files from GitHub, but it is that hidden that nobody is using it! We want to give this feature more visibility and improve the workflow. Related issue: https://github.com/openSUSE/open-build-service/issues/242

- The watchlist is used to bookmark projects. It is already a useful and very used feature, but because of that we want to improve it's usability. We want to allow give an alias to the projects there, grouping projects for long lists and indicate when you are in a bookmarked page.

- On the web site of a repository belonging to a project, there is no obvious way to add it to a package manager, such as zypper. Related issue: https://github.com/openSUSE/open-build-service/issues/407

**Deliverable:**

The UI / UX of OBS improved:
- The project monitor page scales.
- Multiple files can be added altogether.
- Items in the project watchlist can be managed (alias handling, grouping, etc.).
- Projects provide way to choose a distribution and depending on that provide a link to the repository.

**Mentors:** @Ana06, @bgeuken, @ChrisBr 

**Skills:** UI/UX knowledge, HTML, Ruby, Ruby on Rails and Java Script. Packaging knowledge would also help but is not mandatory. And the most important thing: a great desire to learn! 😉 

**Skill Level:** Hard

**Get started:** 

Pick one of the `good first issue` labelled issues and get in touch with the mentors!
We recommend you to make at least one contribution to the project as that will help you to find out if this is the right project for you and to write a proposal, but you do **not** need to send a lot pull requests. The decision to select a student is made based on the proposal and **not** in the number of previous contributions. And remember that quality is more important than quantity! 😄

**Comment by nipunvashistha** [comment]
Hello @Ana06 @bgeuken ,
I am Nipun Vashistha, an undergrad student at IIT Roorkee. I am primarily a UI/UX designer and front-end developer. I have been doing some research on the OBS system, about what the information architecture of OBS, the different user flows, the stakeholders, and how exactly does the whole packaging system work for Linux distributors.
I feel like the whole system is a bit complex to use, especially for a first time user. A first time user will have a hard time getting all the actions and functions. There is a lot of scope to improve and implement the overall User Experience of the system, especially the search feature and the project flow. 
I want to contribute and work with you on this project. Currently, I'm learning more about Packaging as it is important to about the system you are designing, and also trying to learn Ruby on Rails since I have no previous experience in the same. Can you please tell me how do I proceed?

**Comment by bgeuken** [comment]
Hi @nipunvashistha,
appologies for the late reply. You observation is right OBS is quite complex and has a lot room for improvement in the UI/UX :smile:

In general we recommend to pick one of the [good-first-issue](https://github.com/openSUSE/open-build-service/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue+%3A1st_place_medal%3A%22) issues from our project, like https://github.com/openSUSE/open-build-service/issues/2945 or https://github.com/openSUSE/open-build-service/issues/3118. So that you can get in touch with OBS in an easy way (considering the complexity) and see if this is a GSoC project you would like to work on.

In case you haven't had a look yet, check out the 'How to work with us' section on our [organization](
https://summerofcode.withgoogle.com/organizations/5974416370958336/) page.

For learning rails I can recommend the [railstutorial](https://www.railstutorial.org/book/) as well as the [rails guide](http://guides.rubyonrails.org/). If you want a more interactive way of learning rails you could try out [railsforzombies.org](http://railsforzombies.org/).

In regards of packaging, you could give it a try to package a ruby gem, following [this guide](https://github.com/openSUSE/open-build-service/wiki/Packaging-GEMs). But don't worry. You won't need to do any packaging for working on this issue. It just helps to get the general concept. And that we could teach you during the bonding period :-)

If you have any questions, don't hesitate to ask us :smiley:

And finally, if you find that this project is for you, send us a [proposal](
http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/). The dealine set by google is on 'March 27, 2018 18:00 (CEST)'. :green_heart:

**Comment by parasitecruncher** [comment]
@Ana06 @bgeuken  Can I get some help while writing the gsoc proposal? Is there a mail address or IRC channel we can talk on?

**Comment by Ana06** [comment]
@parasitecruncher sure! You can write me directly by email if you want (anamma06@gmail.com). You can also find both Björn (@bjoern|G) and me (@Ana06) in IRC on the Freenode server. We are usually in the #opensuse-buildservice channel.

**Comment by bgeuken** [comment]
@nipunvashistha @parasitecruncher @anyone_who_is_interested

Just a reminder, the deadline for sending proposals is on March 27, 2018 18:00 (CEST)'. So if you consider sending a proposal, hurry up:-) Of course, if you don't want to apply that's also totally fine :smile:

**Comment by nipunvashistha** [comment]
@bgeuken @Ana06 I am in the process of writing my proposal. I have worked out what changes/features I would want to implement in the whole system, almost ready with the new designs, still figuring out and writing ways to implement the features. I will send it for review in a day or so, I hope it isn't too late for it. 😀 
Hoping to work with you guys in near future!

**Comment by bgeuken** [comment]
Nice, glad to hear that :smile:

**Comment by nipunvashistha** [comment]
@bgeuken @Ana06 I have sent my proposal through the GSoC portal. Writing the proposal was itself a learning task and I am hoping to learn more in the future. Do give me your valuable suggestions in any case. 😃

**Comment by Ana06** [comment]
@nipunvashistha 

> @bgeuken @Ana06 I have sent my proposal through the GSoC portal. Writing the proposal was itself a learning task and I am hoping to learn more in the future. Do give me your valuable suggestions in any case.

Nice! :wink: It would have been nice that you send it before so that we have time to review it, because the application closes in 35 minutes, so it is too late for that now.

**Comment by Ana06** [comment]
Closing as this project is from last year. Please open a new one if this is still a current project. :wink:
