### ISSUE TITLE
Improve people collaboration in the Hackweek tool

### ISSUE THREAD

**Issue by Ana06** [openSUSE/mentoring#89]
**Project Title:** Improve people collaboration in the Hackweek tool

**Description:** 

The Hackweek is the time where SUSE engineers meet with other openSUSE contributors to experiment, innovate & learn interruption-free.

We want to improve the Hackweek tool to increase the colaboration inside the tool, which will lead to more colaboration outside of it as well.

First, we want to improve the comments in projects, as they are the base of communication. We should start by providing a better comment editor which helps us when writing a comment. We already support markdown, but it can be improved by supporting links for urls and rendering shorted and clickable links for other pages inside the Hackwek tool.

We also want to be able to add emojis to the comments 😻  And the most important part, we want to support mentions and notifications. Users should receive an email when being mentioned in a comment, when someone writes in one of his proposals, joins his project, etc. Every user should be able to watch / follow any project as well. A configuration page for notifications and a list of notifications will be implemented as well. Related issues: https://github.com/SUSE/hackweek/issues/97, https://github.com/SUSE/hackweek/issues/143 

We also would like to remind users about important events, such as a Hackweek about to start, new people joining a project, etc. All this will also be rendered in the notification page. On top of that, we could have live feed of what is happening during HackWeek: comments, joins, new projects,
progress ...

Another important point to improve collaboration in all the projects is that all of them have the same visibility. Because of that we need to find a fair way to render the proposals, ensuring the all of them have the same chances to be seen while keep showing some of the most popular ones. Currently we only have into account the likes of a proposal to consider it popular, the popularity concept should also be improved. Projects can already be tagged with involved technologies (tags). We could add a tag-cloud to allow people to easily find projects they are interested in.

Last, but not least we want to give hackweeks an end_date, so the page goes into "sleep mode" automatically after a hackweek, showing a summary what happened (most visited projects,....) instead of pretending it is still hackweek16.

**Deliverable:** Code is merged with the necessary tests to prove each feature created.

**Mentor:** @DavidKang , @differentreality 

**Skills:** Ruby, Ruby on Rails, HTML, Java Script

**Skill Level:** Medium

**Get started:** 

Fork the project and get in touch with the mentors.
We recommend you to make at least one contribution to the project as that will help you to find out if this is the right project for you and to write a proposal, but you do **not** need to send a lot pull requests. The decision to select a student is made based on the proposal and **not** in the number of previous contributions. And remember that quality is more important than quantity! 😄

**Comment by AnkushMalik** [comment]
@Ana06, I have some doubts :
- Are you planning to use any gems for editor or do we have to implement functionality in markdown editor itself?
- And,
> Last, but not least we want to give hackweeks an end_date, so the page goes into "sleep mode" automatically after a hackweek...

what do you meant by 'sleep mode' here ^?

**Comment by Ana06** [comment]
@AnkushMalik please have a little it of patience. We are still finishing the projects for this year GSoC and take into account that this is only oficial when Google announces it. So I recommend you to wait until it is oficial before starting preparing a proposal. You will have more than one month and a half, so do not get stressed. 😉

**Comment by AnkushMalik** [comment]
In watch feature, do you also want to send Emails  like GitHub does?
