### ISSUE TITLE
Create awareness for openQA's environment during screen recognition

### ISSUE THREAD

**Issue by foursixnine** [openSUSE/mentoring#91]
**Project Title:** Create awareness for openQA's environment during screen recognition

**Description:** OpenQA works like an user, that is constantly interacting with a computer, and using a set of pre-defined instructions and looks at the screen every certain ammount of time, to check for reference image, and asks "Does this screen that I'm looking at, match this screenshot? if so, how much? are they similar? how similar? is there any better match?", this is called needle matching, and it's key to openQA's operation.

Currently in openQA you can create needles and assign certain tags, so you can use in the test code certain things that allow you to categorize the content, however there is a need for these screenshots to be tagged better or at least be made aware of their relevance, since a test distribution can be large and span across multiple versions, we would like to allow our test developers to say "Ok, all the needles that have 'certain' tag, are not relevant anymore, therefore they should not be used for a specific version".

How this can be done? maybe by analyzing the database?, by offering an UI component that allows the selection of certain needles based on different statistics like usage? or by build?

The idea includes few different things that should be done:

- Learn what openQA/script/modify_needle does and can do
- Improve the statistics for the needles.

**Deliverable:** An extension to '/admin/needles' or an external tool is provided, with documentation and corresponding integration tests. 

**Mentor:** @foursixnine, @mudler, @coolo 

**Skills:** Go, Perl, Python, HTML, Javascript, UI/UX

**Skill Level:** Easy/Medium

**Get started:** 

- You can start looking here: https://progress.opensuse.org/issues/13950
- Start forking the [openQA](https://github.com/os-autoinst/openQA) and [os-autoinst](https://github.com/os-autoinst/os-autoinst)
- Engage with the development team! We hang out in #opensuse-factory on freenode irc net

**Comment by Ana06** [comment]
Closing as this project is from last year. Please open a new one if this is still a current project. :wink:
