### ISSUE TITLE
Develop Container-based backend for openQA

### ISSUE THREAD

**Issue by mudler** [openSUSE/mentoring#92]
**Project Title:** Develop Container-based backend for openQA

**Description:**  

[openQA](https://github.com/os-autoinst/openQA) is an automated test tool for operating systems and the engine at the heart of openSUSE's automated testing initiative. It provides already several backends that allows testing an O.S. on a variety of architectures and scenarios including baremetal and different kinds of virtualized environment. 

A backend capable of directly interacting with different containers technologies would allow us to test container images before release - that could be really useful and enhance the development and publication workflow of containerized environments.

The new container backend ideally should provide an abstract interface to allow [os-autoinst](https://github.com/os-autoinst/os-autoinst) and the test cases to interact with the specific container technology ( that could be Docker, LXD/LXC, rkt, etc. ) and provide the same integration to our current workflow (e.g. tests that runs under a VM).

If you haven't already, [have a look at openQA in action](https://openqa.opensuse.org/tests).

**Deliverable:** Code is merged with the necessary tests to prove each feature created. Abstract interface design and at least one specific backend container implementation is expected (Docker) .

**Mentor:** @mudler, @foursixnine , @coolo

**Skills:** Perl, Docker/rkt (General knowledge of containerized environment)

**Skill Level:** Medium

**Get started:** 
- Engage with the development team! We hang out in #opensuse-factory on freenode!
- Start forking the [openQA](https://github.com/os-autoinst/openQA) and the [os-autoinst](https://github.com/os-autoinst/os-autoinst) repo
- Discussion starts [here](https://progress.opensuse.org/issues/20246).

**Comment by Aniket-Pradhan** [comment]
Hey!

I am interested in this task. I have some knowledge about Containerized environments, and have worked a bit with Docker before.
Can you guide me from where should I start? OpenQA seems like a big project, and it would be helpful if you could give me a kickstart.

**Comment by Ana06** [comment]
Closing as this project is from last year. Please open a new one if this is still a current project. :wink:
