### ISSUE TITLE
Automate Trollolo usage

### ISSUE THREAD

**Issue by Ana06** [openSUSE/mentoring#93]
**Project Title:** Automate Trollolo usage

**Description:** 

[Trollolo](https://github.com/openSUSE/trollolo) is a command line tool, used by teams using Trello to help them to organise their work, such as for example making really easy to generate burndown charts, prioritising cards, creating backups, integrating with other tools, etc. It is being used by many teams in openSUSE to organise the work in their open source projects.

One feature that would be really useful for Trollolo users is to have a service which runs Trollolo, instead of having to run it manually every day. Trollolo is already collecting data enough to be able to implement that and it would save a lot of effort to people using it. Related issue: https://github.com/openSUSE/trollolo/issues/63

Another part where manual work can be avoided, is the `backup` command. It is really useful, as it creates a local copy of a board, which avoid humans errors when manipulating the Trello board. Its implementation was started but never completed finished, as commands such as `restore` and `diff` are missing.

Before starting with all that, we need to clean up the project. First, the recently addition had increased the already existing problem with the commands. Currently we have many commands and some of them are overlapping which others. It would be needed to plan the commands structure, which will need some conceptual work and documentation. Related issue: https://github.com/openSUSE/trollolo/issues/15

Trollolo test suite also needs some ❤️ . There are many thing untested or tests that are not actually testing what they should and are difficult to modify when changing the code. All new code or old code which is touched during the project will be written following test driven development, improving the test suite. Related issue: https://github.com/openSUSE/trollolo/issues/119

**Deliverable:** We expect to make a new major release with the new features and clean ups.

**Mentor:** @Ana06

**Co-mentor:** @cornelius

**Skills:** Ruby, git and a great desire to learn! :wink:

**Skill Level:** Easy/Medium

**Get started:** 

Pick one of the `good first issue` labelled issues and get in touch with the mentors!
We recommend you to make at least one contribution to the project as that will help you to find out if this is the right project for you and to write a proposal, but you do **not** need to send a lot pull requests. The decision to select a student is made based on the proposal and **not** in the number of previous contributions. And remember that quality is more important than quantity! :smile:

**Comment by Ronaq13** [comment]
Hello @Ana06, I would like to contribute in this. How can I start for this?

**Comment by Ana06** [comment]
Hi @Ronaq13,

As said in the get started section, you can set the project and pick a [good first issue](https://github.com/openSUSE/trollolo/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) (just add a comment in the issue), as this will help you to get familiarise with the project and write a better proposal. :smile: 

There are also other things that you can do that will help you to work on Trollolo and prepare the proposal apart from sending PR, such as reading about scrum, reading trello developer documentation, etc... If you need help to find resources I can also point you to some material.

And if you have doubts do not hesitate to ask! :wink:
