### ISSUE TITLE
Enhance log readability in openQA

### ISSUE THREAD

**Issue by mudler** [openSUSE/mentoring#94]
**Project Title:** Enhance log readability in openQA

**Description:**  

[openQA](https://github.com/os-autoinst/openQA) is an automated test tool for operating systems and the engine at the heart of openSUSE's automated testing initiative. 

Currently openQA is providing capabilities to monitor closely the tests execution state by human operators. Also if manual inspection is not always required, logs from the test executions are the basis to detect incoherences between tests and the system under test or to identify bugs in the products being tested.

What openQA is currently looking forward to, is a clear and a more human-readable form of providing logs, so to ease the detection of errors and reducing its noisiness - reading openQA logs should be as easy as eating a piece of cake :)

**Deliverable:** Code is merged with the necessary tests to prove each feature created.

**Mentor:** @mudler, @foursixnine, @coolo

**Skills:** Perl

**Skill Level:** Easy

**Get started:** 
- Engage with the development team! We hang out in #opensuse-factory on freenode!
- Start forking the [openQA](https://github.com/os-autoinst/openQA) and the [os-autoinst](https://github.com/os-autoinst/os-autoinst) repo
- Discussion starts [here](https://progress.opensuse.org/issues/16180).

**Comment by VishnuM-sopho** [comment]
Hello,
@Ana06 @mudler 
This is something that interests me.
I would really like to contribute to this.
Please let me know how to proceed.
i also have a few doubts regarding the project.

**Comment by mudler** [comment]
Hi @VishnuM-sopho, thanks for showing interest in this issue!

Feel free to ask your questions here or over IRC (in #opensuse-factory on freenode) about the project.

If you want to contribute on this, you need to submit a proposal and it have to be accepted by the openSUSE project (also depends on GSOC available slots). 
The proposal should be sent thru https://summerofcode.withgoogle.com/ in Google Doc format so it can be reviewed :smiley:

**Comment by VishnuM-sopho** [comment]
Hello,

I have submitted a draft proposal through gsoc portal.
Can i get some updates /reviews on that.

What can be improved.

**Comment by Ana06** [comment]
@VishnuM-sopho the mentors will review the proposals ASAP. :wink:

**Comment by Ana06** [comment]
Closing as this project is from last year. Please open a new one if this is still a current project. :wink:
